### ISSUE TITLE
Can you offer lower Compile Environment project?

### ISSUE THREAD

**Issue by blackcoding** [InteractiveComputerGraphics/SPlisHSPlasH#1]
My OS is Win7 and VS2013. When cmake successful, but it have very errors. Or can you offer more detail document which can guide me to run the project correctlly.

**Comment by janbender** [comment]
The problem is probably that we use C++11 which is not completely supported by the VS2013 compiler.

**Comment by janbender** [comment]
I just modified the Readme file to make the C++11 requirement clearer.
