### ISSUE TITLE
Strange behaviour reacting on boundary conditions in DFSPH

### ISSUE THREAD

**Issue by alariq** [InteractiveComputerGraphics/SPlisHSPlasH#103]
Hi, first of all huge thank you not only for a great articles but also for providing the implementation, a thing which a lot of academia papers miss.

I am experimenting with your framework and using DFSPH as it looks like it is the one which is the most robust/performant.
I have a simple 2D scene setup with just one particle (provided below). And observe strange behaviour,  I think I can explain it thoug. Looks like it is related to the fact that kernel gradient is S-curve like, so it influences particle depending on where it is sampled i.e. norm(xi - xj), where xj - is the closest boundary position. And as a result velocity may be changed differently. And because norm(xi-xj) depends on particle speed and delta_time is descreet if we take 2 particles starting to fall from different height ther behaviour when colliding with boundary may  (and it is demonstrated by my very simple setup) be different but not in a way one would expect.

So in my first setup boundary is 15m high and particle does not bounce at all, while in my second setup it is only 14 and particle bounces. It does not depend on a particular dimention it is just that particle "bouncines" would vary greatly depending on its parameters, and what I mean here is that this behaviour is not what one would expect, e.g. particle which falls from higher height may not bounce at all (like in my 15meters boundary example) compared to one which falls from smaller height. 
I also understand that it is not a rigid body simulator, but on the other hand I do not understand how one would verify that particles behave correctly if this behaviour that I observe here is in fact correct.

Thanks again. I'd really like to understand the problem here.

Here is the scene file ( just change its resolution to json)
This one is for 14 meters examplem just change scale to [5, 15, 1.5] to get 15meters example.
[OneParticleSetup_2D.txt](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/6011420/OneParticleSetup_2D.txt)

**Comment by janbender** [comment]
Hm, maybe the time step size in this case is a bit large. This is an extreme case since the particle has no neighbors and then crashes in the ground when it has a quite high velocity. If you reduce the CFL factor, e.g. to 0.25, you will see that it does not bounce anymore.

**Comment by alariq** [comment]
Reducing CLF factor seems to help! (though timestep could become really small). Also if not changing CFL difference in bounce observed even on smaller heights, e.g. 4 vs. 3.3. Looks like the kernel function has a really steep gradient, so to get a similar behaviour really small timestep is necessary.

Anyway, thank you for your help and again thanks for the framework!
