### ISSUE TITLE
GPU computation

### ISSUE THREAD

**Issue by hosseinrezaa** [InteractiveComputerGraphics/SPlisHSPlasH#104]
Hi
I installed the spishsplash in my pc and I run the code in visual studio and in windows. I run the code for different scenes successfully but I am not sure that I am using the GPU or not. How can I check that GPU is running? my device is Nvidia Quadro P1000.

**Comment by janbender** [comment]
Only the neighborhood search is implemented on the GPU. You should activate the CMake flag USE_GPU_NEIGHBORHOOD_SEARCH.
