### ISSUE TITLE
Is there any way I can see the number of points of SPlisHSPlasH surface sampling?

### ISSUE THREAD

**Issue by HanlinGao** [InteractiveComputerGraphics/SPlisHSPlasH#106]
Hi, when I try SPHSimulator with DamBreakModel, I can see there is the number of fluid particles in the output log, but there is no boundary particles.
Is the boundary also consisted of particles? or is there any way I can make it also made of particles and see the number of static particles?

Thanks

**Comment by janbender** [comment]
SPlisHSPlasH uses by default the volume maps boundary handling. A volume map is an implicit representation of the boundary which allows better results than using boundary particles. However, if you need boundary particles, then set the option "boundaryHandlingMethod" in the scene file to 0. 

Here is the documentation: 

https://splishsplash.readthedocs.io/en/latest/file_format.html#simulation
