### ISSUE TITLE
AttributeError: module 'pysplishsplash.GUI' has no attribute 'TweakBar'

### ISSUE THREAD

**Issue by AhmadSaeed2601** [InteractiveComputerGraphics/SPlisHSPlasH#107]
i am getting this error .. how to solve this issue ?

SPlisHSPlasH version: 2.9.1
Output directory: C:/Users/DPL/miniconda3/envs/splash/output/Empty
Load scene file: C:/Users/DPL/miniconda3/envs/splash/data/Scenes/Empty.json
Initialize static boundary simulation
Traceback (most recent call last):
  File "c:/Users/DPL/Desktop/Python/1D_Burgers.py", line 23, in <module>
    main()
  File "c:/Users/DPL/Desktop/Python/1D_Burgers.py", line 10, in main
    gui = sph.GUI.TweakBar
AttributeError: module 'pysplishsplash.GUI' has no attribute 'TweakBar'

**Comment by janbender** [comment]
Did you build the pySPlisHSPlasH for the Anttweakbar? The standard version uses imgui.

**Comment by AhmadSaeed2601** [comment]
i used this method from docs to install ....

git clone https://github.com/InteractiveComputerGraphics/SPlisHSPlasH.git
cd SPlisHSPlasH
python setup.py bdist_wheel
pip install build/dist/pySPlisHSPlasH-2.8.3-cp37-cp37m-win_amd64.whl

then ran this instead of last line ...
pip install build/dist/pySPlisHSPlasH-2.9.1-cp38-cp38-win_amd64.whl

**Comment by janbender** [comment]
Use this line:

gui = sph.GUI.Simulator_GUI_imgui(base)

You also find this in the examples.

**Comment by AhmadSaeed2601** [comment]
thanks this worked ...
i am trying this example from doc 

import pysplishsplash as sph
import pysplishsplash.Utilities.SceneLoaderStructs as Scenes

def main():
    # Set up the simulator
    base = sph.Exec.SimulatorBase()
    base.init(useGui=True,  sceneFile=sph.Extras.Scenes.Empty)

    # Create a tweak bar simulator
    gui = sph.GUI.Simulator_GUI_imgui(base)
    base.setGui(gui)

    # Get the scene and add objects
    scene = base.getScene()
    scene.boundaryModels.append(Scenes.BoundaryData(meshFile="../models/UnitBox.obj", translation=[0., 3.0, 0.], scale=[4., 6., 4.], color=[0.1, 0.4, 0.5, 1.0], isWall=True, mapInvert=True, mapResolution=[25, 25, 25]))
    scene.fluidBlocks.append(Scenes.FluidBlock(id='Fluid', box=Scenes.Box([-1.5, 0.0, -1.5], [-0.5, 2.0, -0.5]), mode=0, initialVelocity=[0.0, 0.0, 0.0]))
    scene.fluidBlocks.append(Scenes.FluidBlock(id='Fluid', box=Scenes.Box([0.5, 0.0, 0.5], [1.5, 2.0, 1.5]), mode=0, initialVelocity=[0.0, 0.0, 0.0]))

    # Run the GUI
    base.run()

if __name__ == "__main__":
    main()


now i get this error 
AttributeError: 'pysplishsplash.Exec.SimulatorBase' object has no attribute 'getScene'

**Comment by janbender** [comment]
It seems that you use an older version of the examples with the new library.
Update the examples or use this line:

scene = sph.Exec.SceneConfiguration.getCurrent().getScene()

**Comment by AhmadSaeed2601** [comment]
thank you so mush for your help ... it worked ..
i am trying to learn these things as i am kind of new to these things 
i will take care of versions next time 
can you please tell me are there any updated examples in the documents
