### ISSUE TITLE
why are the results of VolumeSampling different when used separately and when used in the simulator? 

### ISSUE THREAD

**Issue by HanlinGao** [InteractiveComputerGraphics/SPlisHSPlasH#109]
I tried two ways to generate fluid particles with a radius 0.025.
One is specifying the start and end coordinates in the "FluidBlock" of the .json file.
For example, I specified a start like [-0.5, -0.5, -0.5] and an end like [0.5, 0.5, 0.5], when I run the SPHSimulator, the output information showed it generated 6859 particles.
However, when I used the VolumeSampling tool to sample a unitbox.obj, which is 1 by 1 by 1, it generated 8000 particles, which I think is more reasonable. 
It seems that in SPHSimulator, it will make sure there is one line of particles in the middle first, so when an even number of particles can be sampled along the edge, it will force it into an odd number. Like the example above, the edge is 1, the diameter of particles is 0.05, 1 / 0.05 = 20 particles can be sampled, but it only sampled 19 particles per edge.

Could you tell me why they are different and how to generate 8000 particles in the first way?

**Comment by janbender** [comment]
They are just different since they were implemented at different times in different ways. We put this on our todo list.

**Comment by HanlinGao** [comment]
thanks!
