### ISSUE TITLE
make fails

### ISSUE THREAD

**Issue by coreos-xx** [InteractiveComputerGraphics/SPlisHSPlasH#11]
This is what I am getting. 
Compiler version is gcc 4.9 
OS linux mint 17.2

In file included from Viscosity/Viscosity_Peer2015.h:7:0,
                 from TimeStep.cpp:12:
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:47:10: error: ‘Product’ in namespace ‘Eigen’ does not name a template type
   Eigen::Product<MatrixReplacement, Rhs, Eigen::AliasFreeProduct> operator*(const Eigen::MatrixBase<Rhs>& x) const
          ^
In file included from Viscosity/Viscosity_Peer2015.h:7:0,
                 from TimeStep.cpp:12:
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:69:38: error: ‘StorageIndex’ in ‘using SystemMatrixType = class Eigen::SparseMatrix<double> {aka class Eigen::SparseMatrix<double>}’ does not name a type
   typedef typename SystemMatrixType::StorageIndex StorageIndex;
                                      ^
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:84:10: error: ‘Index’ in namespace ‘Eigen’ does not name a type
   Eigen::Index rows() const { return m_dim; }
          ^
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:85:10: error: ‘Index’ in namespace ‘Eigen’ does not name a type
   Eigen::Index cols() const { return m_dim; }
          ^
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:119:23: error: ‘Solve’ in namespace ‘Eigen’ does not name a template type
   inline const Eigen::Solve<JacobiPreconditioner, Rhs> solve(const Eigen::MatrixBase<Rhs>& b) const
                       ^
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:141:10: error: ‘generic_product_impl’ is not a class template
   struct generic_product_impl<MatrixReplacement, Rhs, SparseShape, DenseShape, GemvProduct> // GEMV stands for generic matrix-vector
          ^
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:141:55: error: ‘SparseShape’ was not declared in this scope
   struct generic_product_impl<MatrixReplacement, Rhs, SparseShape, DenseShape, GemvProduct> // GEMV stands for generic matrix-vector
                                                       ^
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:141:68: error: ‘DenseShape’ was not declared in this scope
   struct generic_product_impl<MatrixReplacement, Rhs, SparseShape, DenseShape, GemvProduct> // GEMV stands for generic matrix-vector
                                                                    ^
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:142:31: error: expected template-name before ‘<’ token
    : generic_product_impl_base<MatrixReplacement, Rhs, generic_product_impl<MatrixReplacement, Rhs> >
                               ^
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:142:31: error: expected ‘{’ before ‘<’ token
../SPlisHSPlasH/Utilities/MatrixFreeSolver.h:142:31: error: expected unqualified-id before ‘<’ token
make[2]: *** [SPlisHSPlasH/CMakeFiles/SPlisHSPlasH.dir/TimeStep.cpp.o] Error 1
make[1]: *** [SPlisHSPlasH/CMakeFiles/SPlisHSPlasH.dir/all] Error 2
make: *** [all] Error 2

**Comment by janbender** [comment]
This seems to be a problem with Eigen. Did you use a 64bit build target?

**Comment by coreos-xx** [comment]
Yes 64 bit
