### ISSUE TITLE
Choosing boundary particles

### ISSUE THREAD

**Issue by hosseinrezaa** [InteractiveComputerGraphics/SPlisHSPlasH#111]
Hi
consider a water droplet with thousands of particles. Is it possible to choose the particles which are on the surface of the droplet (for example in order to apply a force or velocity,... only to the surface of the droplet)? If yes how can I have access to the surface particles in the code?
Regards

**Comment by hosseinrezaa** [comment]
I mean the surface particles

**Comment by janbender** [comment]
There is not direct way to get the surface particles. However, using a color field is a very simple method to do this in SPH.

**Comment by hosseinrezaa** [comment]
I checked the Gissler2017 paper. It is almost what I want. But I have a question. Is it possible to impose this drag force regionally?
It seems that this drag force is applied to the whole domain. If we want to apply it for example to the y<1 domain. Is it possible?
