### ISSUE TITLE
particle radius

### ISSUE THREAD

**Issue by hosseinrezaa** [InteractiveComputerGraphics/SPlisHSPlasH#112]
Hi
I am simulating the code with particles with a radius of 0.005 and the number of particles are 20000. But when I change the radius from 0.005 to 0.003 a problem appears. when the particles reach the solid body, they are exploding.
Is there any restriction for the particle radius?
Regards

**Comment by janbender** [comment]
There is no restriction. However, if the dimension of the particles gets smaller, you probably also have to adapt the time step size. You could also try with a different boundary handling (Akinci).
