### ISSUE TITLE
python setup.py bdist_wheel 

### ISSUE THREAD

**Issue by qwerdf4** [InteractiveComputerGraphics/SPlisHSPlasH#114]
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'pysplishsplash', '--config', 'Release', '--', '/m']' returned non-zero exit status 1

**Comment by digitalillusions** [comment]
Hi @qwerdf4, unfortunately this doesn't tell us much about whats going wrong for you. Could you share a little more about the error message? Do you have CMake and a valid c++ compiler installed?
