### ISSUE TITLE
error: wgl: the driver does not appear to support opengl

### ISSUE THREAD

**Issue by hosseinrezaa** [InteractiveComputerGraphics/SPlisHSPlasH#115]
Hi
I Have installed your software on my different computers and I have no problem. But recently I tried to install it on a pc with a Nvidia Tesla T4 graphic card. I used CMAKE and it was Ok even the scene window opened.

![1](https://user-images.githubusercontent.com/48132503/119669378-4e895080-be38-11eb-9e3a-a7af7d80cad6.png)

 **But when I selected a scene this error appeared.**

error: wgl: the driver does not appear to support opengl

![2](https://user-images.githubusercontent.com/48132503/119669652-81cbdf80-be38-11eb-9530-619fcfafbe08.png)

Is there any solution to this problem?

Regards

**Comment by janbender** [comment]
Try with a different driver or start the simulation without gui by using the --no-gui flag.
