### ISSUE TITLE
Motors

### ISSUE THREAD

**Issue by piero-A662P** [InteractiveComputerGraphics/SPlisHSPlasH#118]
Hi to everybody,
were can I find documentation about " **TargetVelocityMotorHingeJoints:** " ?
This feature is used in _MotorScene2.json_ example and I wish like to know more about the command.
Many thanks, bye 
. . . Piero

**Comment by janbender** [comment]
Sorry, but this is not documented yet. In fact you can use any joint which is supported by our library PositionBasedDynamics in the scene file. The motor definition looks like this:

```
"RigidBodies": [
		{
			"id": 0,
			"geometryFile": "../models/UnitBox.obj",
			"translation": [0,1,0],
			"rotationAxis": [1, 0, 0],
			"rotationAngle": 0,
			"scale": [2, 2, 2],
			"color": [0.1, 0.4, 0.6, 1.0], 
			"isDynamic": false,
			"isWall": true,
			"mapInvert": true, 
			"mapThickness": 0.0,
			"mapResolution": [25,25,25]
		},
		{
			"id": 1,
			"geometryFile": "../models/UnitBox.obj",
			"translation": [0,0.1,0],
			"rotationAxis": [1, 0, 0],
			"rotationAngle": 0,
			"scale": [1.5,0.1,0.2],
			"color": [0.1, 0.4, 0.6, 1.0], 
			"density": 10000,
			"isDynamic": true,
			"isWall": false,
			"mapInvert": false, 
			"mapThickness": 0.0,
			"mapResolution": [20,20,20]
		}
	],
	"TargetVelocityMotorHingeJoints": [
		{
			"bodyID1": 1,
			"bodyID2": 0,
			"position": [0,0,0],
            "axis": [0,1,0],
            "repeatSequence": 1,
            "targetSequence": [0,-5,1,5,2,-5]
		}
	],
```

This motor links the two rigid bodies with the user-defined ids 0 and 1. The hinge axis is defined by the world space position (0,0,0) and the direction vector (0,1,0). So it points in the direction of the y-axis and lies in the origin. "repeatSequence" means that the motor sequence is repeated infinitely. And the "targetSequence": [0,-5,1,5,2,-5] is a definition of keyframes. This is always a pair of time and target velocity. So at time 0 the motor has a velocity of -5, at time 1 it changes to 5 and at time 2 it changes to -5 and then the sequence starts again. 

Hope that helps!

**Comment by piero-A662P** [comment]
Yes, this helps. Many thanks.

Piero
