### ISSUE TITLE
How to install PartioViewer?

### ISSUE THREAD

**Issue by W-Alex-Y** [InteractiveComputerGraphics/SPlisHSPlasH#119]
After I installed pySplishSplash by pip.

It's okay to use the command line "splash" to generate fluid simulation scenes.

I followed the tutorial
> To visualize a sequence of partio files or a single file, call (the index in the file name is used for the sequence):
PartioViewer fluid_data_1.bgeo

But it reported:
> partioviewer: command not found

I've searched  a lot but cannot find the instruction about install PartioViewer.
It'll be great help if anyone can tell me how to install this tool.

Thx a lot!

**Comment by digitalillusions** [comment]
Hi, as of right now we don't have python bindings for the tools. If you want to use the `partioviewer` you would have to compile it yourself. We are working on creating bindings for all the tools in the future, but can unfortunately not give an eta,

**Comment by W-Alex-Y** [comment]
> Hi, as of right now we don't have python bindings for the tools. If you want to use the `partioviewer` you would have to compile it yourself. We are working on creating bindings for all the tools in the future, but can unfortunately not give an eta,

Got it. Thx!
