### ISSUE TITLE
Different speeds in different systems 

### ISSUE THREAD

**Issue by hosseinrezaa** [InteractiveComputerGraphics/SPlisHSPlasH#121]
Hi
I am using CPU simulation of a model to simulate in SPLISHSPLASHin two different systems. Everything is similar and we are using CPU simulation not GPU.
The question is that the powerful system is slower. 

![image](https://user-images.githubusercontent.com/48132503/135607508-17635cc1-d709-4117-b53a-bc3813c46b12.png)

The weaker system is faster

![image](https://user-images.githubusercontent.com/48132503/135607598-2834e9af-866e-426b-8e73-94a4cd82b48b.png)

Is there anything that should be adjusted in the powerful system?

**Comment by hosseinrezaa** [comment]
the weaker system is a pc that I am using and the more powerful system is a workstation that I connect using a remote desktop and run the program

**Comment by janbender** [comment]
Performance tests with just 125 particles are misleading. Then the overhead for the parallelization is higher than the benefit. Try to test this with more particles, e.g. 1 million particles. Then you should see clearly a difference.
