### ISSUE TITLE
using boundary handling method

### ISSUE THREAD

**Issue by hosseinrezaa** [InteractiveComputerGraphics/SPlisHSPlasH#123]
Hi
I am using Bender et al boundary handling method.
There are some fluid particles (blue particles) that are crossing between ice floes. I input ice floes with object files. But it seems that fluid particles cannot see the ice floes properly and pass through the ice floes. But this problem will not happen when I use Acinci et al 2012.

What is the problem?

Regards

![image](https://user-images.githubusercontent.com/48132503/136995981-8b794bf0-0903-4538-bae7-586b862916a2.png)

**Comment by janbender** [comment]
Yes, e.g. DamBreakModelDragons.json.
