### ISSUE TITLE
demo error

### ISSUE THREAD

**Issue by ByLele** [InteractiveComputerGraphics/SPlisHSPlasH#126]
when i try command ./SPHSimulator ../data/Scenes/DoubleDamBreak.json
Error:   X11: The DISPLAY environment variable is missing

**Comment by janbender** [comment]
It seems that you cannot run OpenGL code on your system. Can you start glxgears?

**Comment by ByLele** [comment]
thank you&nbsp;



---Original---
From: "Jan ***@***.***&gt;
Date: Tue, Nov 2, 2021 16:39 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [InteractiveComputerGraphics/SPlisHSPlasH] demo error (Issue #126)




 
It seems that you cannot run OpenGL code on your system. Can you start glxgears?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
