### ISSUE TITLE
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! (with GLSL '#version 330 ')

### ISSUE THREAD

**Issue by ytimber** [InteractiveComputerGraphics/SPlisHSPlasH#135]
Hi,

I'm a newcomer to computer graphics so I'm a little confused on how I can solve this issue. In the code posted in Github under  ``` SPlisHSPlasH/extern/imgui/imgui_impl_opengl3.cpp```, the author wrote 'If you get an error please report on GitHub. You may try different GL context version or GLSL version.' I wonder what does it mean and what I should do. Many thanks!

```SPlisHSPlasH version: 2.11.1
Output directory: /home/ccn/Downloads/SPlisHSPlasH/bin/output/DoubleDamBreak
Load scene file: /home/ccn/Downloads/SPlisHSPlasH/data/Scenes/DoubleDamBreak.json
Initialize static boundary simulation
Initialize fluid particles
Number of fluid particles: 4732
OpenGL version 3.0
Vendor: Intel Open Source Technology Center
Renderer: Mesa DRI Intel(R) UHD Graphics 630 (CFL GT2)
Version: 3.0 Mesa 20.0.8
Loading /home/ccn/Downloads/SPlisHSPlasH/data/models/UnitBox.obj
Number of triangles: 12
Number of vertices: 8
Loaded cached volume map: /home/ccn/Downloads/SPlisHSPlasH/data/Scenes/Cache/UnitBox_sb_vm_0.025_s3.1_3.1_3.1_r25_25_25_i1_t0.cdm
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! (with GLSL '#version 330
')
error: vertex shader lacks `main'

Segmentation fault (core dumped)
```

**Comment by janbender** [comment]
Seems that your graphics device is not supported by the external library imgui. Maybe a driver update could help.

**Comment by ytimber** [comment]
@janbender Thank you so much! 
Also, I'm wondering how do you render the scenes from the particles generated (.bgeo or .vtk files)? Such as the water scene on the front page of Github. Did you use Blender for this? How did you set up the rendering parameters? Many thanks!
