### ISSUE TITLE
Can you tell me how to generate the surface of the fluid?

### ISSUE THREAD

**Issue by hongshul** [InteractiveComputerGraphics/SPlisHSPlasH#14]
Hi, 
I run your code successfully. However I meet a question how to get the surface of the fluid. 
Cheers

**Comment by janbender** [comment]
For the surface reconstruction we use an external tool: 
http://www.mootzoid.com/plugin/empolygonizer5

**Comment by hongshul** [comment]
Thanks for the answer!
