### ISSUE TITLE
Clarify licenses of external dependencies

### ISSUE THREAD

**Issue by Andlon** [InteractiveComputerGraphics/SPlisHSPlasH#152]
The README currently only mentions (very briefly) that the library is licensed under the MIT license. However, the repository also contains external code (primarily in the `extern` folder, I believe?) which is covered by separate licenses. This needs to be clarified. I would suggest a `License` header in the README clarifying what code is covered by the license, and what code is covered by separate licenses, as is customary in other projects. For example, perhaps something along the lines of:

```
# License

External dependencies are covered by separate licensing terms.
See the `extern` folder for the code and respective licensing terms of each dependency.

The SPlisHSPlasH library code is licensed under the MIT license. See `LICENSE` for details.
```

**Comment by janbender** [comment]
Good point. I added this info.
