### ISSUE TITLE
AttributeError: module 'pysplishsplash' has no attribute 'Simulator_GUI_TweakBar'

### ISSUE THREAD

**Issue by Ricahrd-Li** [InteractiveComputerGraphics/SPlisHSPlasH#161]
Hi, I am interested in this awesome project and try to learn and use it.

I install with directly `pip install pysplishsplash` 

However, at the start, I have tried this first minimal example from [link to doc](https://splishsplash.readthedocs.io/en/latest/py_getting_started.html#minimal-working-example)
by runing:
```python
import pysplishsplash as sph

def main():
    base = sph.Exec.SimulatorBase()
    base.init()
    gui = sph.GUI.Simulator_GUI_TweakBar(base)
    base.setGui(gui)
    base.run()

if __name__ == "__main__":
    main()
```
I get error:
```
AttributeError: module 'pysplishsplash' has no attribute 'Simulator_GUI_TweakBar'
```

Then I change `TweakBar` to `imgui`, it works well:
```python
import pysplishsplash as sph

def main():
    base = sph.Exec.SimulatorBase()
    base.init()
    gui = sph.GUI.Simulator_GUI_imgui(base)
    base.setGui(gui)
    base.run()

if __name__ == "__main__":
    main()
```

**Comment by janbender** [comment]
Thanks for the hint. I just updated the documentation file. So the next release will fix this.
