### ISSUE TITLE
erros when building under linux

### ISSUE THREAD

**Issue by chunleili** [InteractiveComputerGraphics/SPlisHSPlasH#174]
two fatal errors occur when building in the manjaro! 

building tools: cmake and make

> /home/cl/codes/my/SPlisHSPlasH/extern/Catch2/catch.hpp:8223:45: error: size of array ‘altStackMem’ is not an integral constant-expression
 8223 |     char FatalConditionHandler::altStackMem[sigStackSize] = {};

> /home/cl/codes/my/SPlisHSPlasH/extern/Catch2/catch.hpp:8164:58: error: call to non-‘constexpr’ function ‘long int sysconf(int)’
 8164 |     constexpr static std::size_t sigStackSize = 32768 >= MINSIGSTKSZ ? 32768 : MINSIGSTKSZ;
      |                                                          ^~~~~~~~~~~

![image](https://user-images.githubusercontent.com/48758868/166238587-2cdc46a2-d0bb-4f26-97b5-b6f27eb88650.png)

![image](https://user-images.githubusercontent.com/48758868/166237422-2d83827b-1e10-4afc-b9cf-49fa9dd4e0da.png)

**Comment by digitalillusions** [comment]
Hi, thanks for reporting this issue. It seems that this can be fixed by simply upgrading the version of `Catch2`. If you want a quick fix, just exchange the header `extern/Catch2/catch.hpp` with a more recent version and everything should work fine. We're working on pushing a fix soon.

**Comment by chunleili** [comment]
> Hi, thanks for reporting this issue. It seems that this can be fixed by simply upgrading the version of `Catch2`. If you want a quick fix, just exchange the header `extern/Catch2/catch.hpp` with a more recent version and everything should work fine. We're working on pushing a fix soon.

thanks！
