### ISSUE TITLE
The referenced paper may be wrong

### ISSUE THREAD

**Issue by chunleili** [InteractiveComputerGraphics/SPlisHSPlasH#178]
In SPlisHSPlasH\Viscosity\Viscosity_Peer2016.h and SPlisHSPlasH\Elasticity\Elasticity_Peer2018.h, the author quoted the same paper:

[PGBT17] Andreas Peer, Christoph Gissler, Stefan Band, and Matthias Teschner. An implicit SPH formulation for incompressible linearly elastic solids. Computer Graphics Forum, 2017. URL: http://dx.doi.org/10.1111/cgf.13317

It is obviously wrong for the viscosity method, because it is about the elasticity. Moreover, the name of the file should be "Elasticity_Peer2017" rather than 2018 according to your naming convention.

**Comment by janbender** [comment]
Thanks for pointing this out. I will correct it in the next version
