### ISSUE TITLE
Installation in Windows

### ISSUE THREAD

**Issue by Rajatpareek** [InteractiveComputerGraphics/SPlisHSPlasH#182]
Hey there, I am facing an issue during installation. After configuration and generation in Cmake, when I am opening project its not creating SPHSimualator.exe anywhere also no bin folder created. Instead of this I am getting different file type simulators like vcproj etc. in build.
Can someone please guide me for installation.
Thank you in advance

**Comment by WeilerMarcel** [comment]
Hi @Rajatpareek,
it sounds like you only generated configured the cmake project and generated the Visual Studio project file. You will have to open that project in Visual Studio and build the executable afterwards.

![cmake](https://user-images.githubusercontent.com/18287644/171366435-38a1ed6b-ee1c-4b47-9e45-ae08e61ecf35.png)

Alternatively you can use CMake from the command line to drive the Visual Studio compiler. To do that, switch into your build directory after configuring/generating the project and call `cmake --build . --config Release`.
