### ISSUE TITLE
Partio export

### ISSUE THREAD

**Issue by tnwells** [InteractiveComputerGraphics/SPlisHSPlasH#19]
I am fairly new to animation and I was wondering about the export format of the simulations. I see that the individual frames are saved to .bgeo files, but I am having trouble figuring out what to do with those. I see that they are viewable with the PartioViewer, but I have only been able to view the individual frames that way. I was wondering how to view the files created by the simulations as a video.

**Comment by janbender** [comment]
bgeo files can be directly imported in Houdini. For Maya you need an additional plugin like: 

http://redpawfx.github.io/partio/

Or you can use these files to reconstruct the surface of the fluids with tools like: 

http://www.mootzoid.com/plugin/empolygonizer5

**Comment by tnwells** [comment]
Awesome, thanks for the information!
