### ISSUE TITLE
Issue with high velocities at certain time-steps in simulator

### ISSUE THREAD

**Issue by arjun-mani** [InteractiveComputerGraphics/SPlisHSPlasH#191]
Hello,

Thanks for building this great simulator. I have been noticing an issue recently with very high velocities at certain points in the simulator. In my simulations, at certain time-steps the positions  change very suddenly. I've noticed it both using pysplishsplash with the current version, and I've also back-tested with some previous versions (2.4.0/2.5.0). (I am obtaining the positions by reading partio files that I export with 200 fps). For example, the transition from step 99 to 100 has a small difference (average absolute delta of 0.0017), but the transition from step 100 to 101 has a *much* bigger difference (average delta of 0.166, with max values of ~0.75). It seems to me that this cannot be physically possible. I have noticed these issues often occur on time-steps x99 or x00 for some x. Over the whole simulation, there are many instances where a particle suddenly has a delta position of 0.6-0.7, in a box of dimensions 0.75x0.75x0.75.

I've attached a config where this occurs. I'm just doing a single fluid cube in a rigid cube, and increasing the viscosity doesn't seem to alleviate the issue. I would really, really appreciate your help on this issue. I am trying to train a model using the simulator as ground-truth, and I think these sudden velocity explosions at certain time-steps are causing training issues. I think this is potentially the problem. Thank you so much in advance.

[train0.json.zip](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/9228180/train0.json.zip)

**Comment by janbender** [comment]
Hi,

Can you try again but turn off the z-sort? The simulator sorts all particles each 500 steps to improve cache hits. They all have still the same ID but not the same order.

Hope that helps! 


Am 31. Juli 2022 08:40:28 MESZ schrieb Arjun Mani ***@***.***>:

**Comment by arjun-mani** [comment]
This solved the issue. Thanks so much!

**Comment by arjun-mani** [comment]
This solved the issue. Thanks so much!
