### ISSUE TITLE
Adapt PBD solver 2.0.1

### ISSUE THREAD

**Issue by yangfengzzz** [InteractiveComputerGraphics/SPlisHSPlasH#197]
I found there are alot API changes in PBD 2.0.1. In SPH code, PBDWrapper is releated to such modification.

#167  only fix the link with old pbd code. how can I fix it to adapt this new pbd solver?

**Comment by janbender** [comment]
That is a good point. I just recognized that the PBD version SPlisHSPlasH uses is not up-to-date. I will put this on my todo list.

**Comment by janbender** [comment]
I just updated to the new PBD version.
