### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by andrewcoughtrie** [InteractiveComputerGraphics/SPlisHSPlasH#2]
I'm getting the following error when attempting to compile SPlisHSPlasH. I'm compiling on Xubuntu 16.04 using cmake 3.5.2 and gcc 6.2.0. Any ideas what is going wrong?

`/home/andy/Programs/SPlisHSPlasH/Utilities/FileSystem.cpp: In static member function ‘static std::__cxx11::string SPH::FileSystem::getProgramPath()’:
/home/andy/Programs/SPlisHSPlasH/Utilities/FileSystem.cpp:171:40: error: ‘getpid’ was not declared in this scope
  sprintf(szTmp, "/proc/%d/exe", getpid());
                                        ^
/home/andy/Programs/SPlisHSPlasH/Utilities/FileSystem.cpp:172:57: error: ‘readlink’ was not declared in this scope
  int bytes = std::min((int) readlink(szTmp, buffer, 1000), 999);
                                                         ^
make[2]: *** [Utilities/CMakeFiles/Utilities.dir/FileSystem.cpp.o] Error 1
make[1]: *** [Utilities/CMakeFiles/Utilities.dir/all] Error 2
make: *** [all] Error 2`

**Comment by janbender** [comment]
Does it help if you add #include <unistd.h> in the beginning of FileSystem.cpp?

**Comment by andrewcoughtrie** [comment]
Including unistd.h gets it past that error but it now fail when building DynamicBoundaryDemo. I've included the first part of the error below and attached the entire output from make here -
[error.txt](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/661075/error.txt) - the error is from line 116 of the error.txt file.

`<command-line>:0:0: warning: "PBD_DATA_PATH" redefined
<command-line>:0:0: note: this is the location of the previous definition
In file included from /apps/compilers/GCC/6.2.0/build/include/c++/6.2.0/parallel/algorithmfwd.h:34:0,
                 from /apps/compilers/GCC/6.2.0/build/include/c++/6.2.0/parallel/algorithm:35,
                 from /home/andy/Programs/SPlisHSPlasH/extern/install/CompactNSearch/include/Config.h:14,
                 from /home/andy/Programs/SPlisHSPlasH/extern/install/CompactNSearch/include/CompactNSearch.h:5,
                 from /home/andy/Programs/SPlisHSPlasH/SPlisHSPlasH/FluidModel.h:7,
                 from /home/andy/Programs/SPlisHSPlasH/SPlisHSPlasH/TimeStep.h:5,
                 from /home/andy/Programs/SPlisHSPlasH/Demos/Common/DemoBase.h:7,
                 from /home/andy/Programs/SPlisHSPlasH/Demos/DynamicBoundaryDemo/main.cpp:14:
/apps/compilers/GCC/6.2.0/build/include/c++/6.2.0/parallel/tags.h: In member function ‘__gnu_parallel::_ThreadIndex __gnu_parallel::parallel_tag::__get_num_threads()’:
/apps/compilers/GCC/6.2.0/build/include/c++/6.2.0/parallel/tags.h:66:38: error: ‘omp_get_max_threads’ was not declared in this scope
           return omp_get_max_threads();`

**Comment by bartoszek** [comment]
Have the same problem on Archlinux (cmake 3.9.2, gcc6 6.4.1)
[build-log.txt](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/1338228/build-log.txt)

**Comment by janbender** [comment]
It seems that the compiler does not find OpenMP. However, since I cannot reproduce this error on my system it is hard to help you.

**Comment by bartoszek** [comment]
It looks like `-fopenmp` is not getting propagated to `Demos` builds

`make VERBOSE=1`
`
[ 95%] Building CXX object Demos/DynamicBoundaryDemo/CMakeFiles/DynamicBoundaryDemo.dir/main.cpp.o
cd /home/bartus/AUR/splishsplash/src/splishsplash/build/Demos/DynamicBoundaryDemo && /usr/bin/clang++  -DPBD_DATA_PATH=\"../data\" -DPBD_DATA_PATH=\"/home/bartus/AUR/splishsplash/src/splishsplash/extern/install/PositionBasedDynamics/include/data\" -DSPH_DATA_PATH=\"../data\" -DTW_NO_LIB_PRAGMA -DTW_STATIC -DUSE_PBD -D_CRT_SECURE_NO_DEPRECATE -I/home/bartus/AUR/splishsplash/src/splishsplash -I/home/bartus/AUR/splishsplash/src/splishsplash/extern/freeglut/include -I/usr/include/eigen3 -I/home/bartus/AUR/splishsplash/src/splishsplash/extern/install/CompactNSearch/include -I/home/bartus/AUR/splishsplash/src/splishsplash/extern/install/PositionBasedDynamics/include -I/home/bartus/AUR/splishsplash/src/splishsplash/extern/glew/include  -march=native -mtune=native -O2 -pipe -fstack-protector-strong -fno-plt   -std=gnu++11 -o CMakeFiles/DynamicBoundaryDemo.dir/main.cpp.o -c /home/bartus/AUR/splishsplash/src/splishsplash/Demos/DynamicBoundaryDemo/main.cpp
`
append `-fopenmp` to `CMakeFiles/DynamicBoundaryDemo.dir/flags.make` fixes the problem.

**Comment by bartoszek** [comment]
Also when building with gcc7/clang5 there are some minor hiccups:
```
/home/bartus/AUR/splishsplash/src/splishsplash/extern/partio/src/lib/io/MC.cpp: In function ‘int Partio::CharArrayLen(char**)’
/home/bartus/AUR/splishsplash/src/splishsplash/extern/partio/src/lib/io/MC.cpp:107:21: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
     if(charArray != false){
                     ^~~~~
/home/bartus/AUR/splishsplash/src/splishsplash/extern/partio/src/lib/io/MC.cpp:108:31: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
         while(charArray[i] != '\0'){
```
```
In file included from /home/bartus/AUR/splishsplash/src/splishsplash/extern/partio/src/lib/io/NEW_BGEO.cpp:45:0:
/home/bartus/AUR/splishsplash/src/splishsplash/extern/partio/src/lib/io/PartioBinaryJson.h: In member function ‘void Partio::JSONParser<DELEGATE>::numberDataNotify()’
/home/bartus/AUR/splishsplash/src/splishsplash/extern/partio/src/lib/io/PartioBinaryJson.h:330:31: error: expected primary-expression before ‘>’ token
         Derived().numberData<T>(currKey,val);
                               ^
/home/bartus/AUR/splishsplash/src/splishsplash/extern/partio/src/lib/io/PartioBinaryJson.h: In member function ‘void Partio::JSONParser<DELEGATE>::uniformArray()’
/home/bartus/AUR/splishsplash/src/splishsplash/extern/partio/src/lib/io/PartioBinaryJson.h:336:37: error: expected primary-expression before ‘>’ token
         if(!Derived().uniformArray<T>(currKey,length)){
 ```

**Comment by janbender** [comment]
I will test your patch and integrate it. Thanks. 

Partio is an external library. So it would be helpful if you send your problem to the authors of this lib.

**Comment by bartoszek** [comment]
Latest version of partio have this solved.

30 wrz 2017 3:28 PM "Jan Bender 'notifications@github.com' via 33Mail" <
sender@mailer1.33mail.com> napisał(a):

**Comment by janbender** [comment]
Thanks for the hint. I will try to update partio.
