### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by bladomas** [InteractiveComputerGraphics/SPlisHSPlasH#21]
Greetings,

I was redirected to this SPH code when I was on the CFD online forums, I am in need of SPH codes that can simulate blood flow (initially simple cylinders with static walls).

I personally have very little experience with Cmake or SPH, so I was wondering whether some tutorials were available to get used to the code? Or perhaps I could receive some useful tips on how to get started. 

Kind regards,
Dominykas

**Comment by janbender** [comment]
Hi, 

there is no tutorial for SPlisHSPlasH yet. To start you need to install Cmake and Git. 
If you need some information about SPH, maybe you can take a look in the state-of-the-art report about SPH by Ihmsen et al. 2014. 

Jan

**Comment by bladomas** [comment]
I'm currently working on Linux, and there were some errors I thought. I will check it out tomorrow and let you know.  Thanks for your replies.

**Comment by bladomas** [comment]
I get the error, "Could NOT find GLUT ..." I believe I cannot post a picture here. I copied the error below:

CMake Error at /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GLUT (missing: GLUT_glut_LIBRARY GLUT_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake3/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake3/Modules/FindGLUT.cmake:116 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  Demos/DynamicBoundaryDemo/CMakeLists.txt:8 (find_package)


-- Configuring incomplete, errors occurred!
