### ISSUE TITLE
Minimalistic Dockerfile for GPU build

### ISSUE THREAD

**Issue by fabiocruz** [InteractiveComputerGraphics/SPlisHSPlasH#231]
Hi there!

I am trying to write a Dockerfile that builds SPlisHSPlasH with GPU support, but I am facing some issues.

Here is my Dockerfile. I am interested in building primarily the executable, ie tools and other external packages are not relevant.

```dockerfile
FROM nvidia/cuda:11.2.0-devel-ubuntu20.04

# Set frontend to be noninteractive, to avoid prompts during installation.
ENV DEBIAN_FRONTEND=noninteractive

# Install SPlisHSPlasH dependencies.
RUN apt-get update -y \
    && apt-get install -y git cmake xorg-dev freeglut3-dev build-essential
   
# Install Python.
RUN apt install -y python3 python3-setuptools python3-pip

# Clone SPlisHSPlasH.
WORKDIR /
RUN git clone https://github.com/InteractiveComputerGraphics/SPlisHSPlasH.git

WORKDIR /SPlisHSPlasH/build

# Build SPlisHSPlasH.
RUN cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DUSE_PYTHON_BINDINGS=OFF \
    -DUSE_GPU_NEIGHBORHOOD_SEARCH=ON \
    ..

RUN make
```

This correctly builds the package until it starts building tools, at which point it fails to find the neighbour search module. Here is the relevant part of the build log:
```text
[ 76%] Building CXX object Tools/FoamGenerator/CMakeFiles/FoamGenerator.dir/main.cpp.o
/SPlisHSPlasH/Tools/FoamGenerator/main.cpp:7:10: fatal error: CompactNSearch.h: No such file or directory
    7 | #include "CompactNSearch.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

I tried commenting out some tools, and it solves the problem. Here is my `Tools/CMakeLists.txt`:
```cmake
# add_subdirectory(PartioViewer)
# add_subdirectory(FoamGenerator)
add_subdirectory(SurfaceSampling)
# add_subdirectory(VolumeSampling)
add_subdirectory(partio2vtk)
# add_subdirectory(MeshSkinning)
add_subdirectory(ParameterParser)
```

Is there an option that I could use to avoid installing these tools without manually changing `Tools/CMakeLists.txt`? Or alternatively could this be a bug in the tools?

This problem does not occur when I build SPlisHSPlasH without GPU support, ie with `-DUSE_GPU_NEIGHBORHOOD_SEARCH=OFF`.

**Comment by janbender** [comment]
Hi, some of the tools still require CompactNSearch. We already solved this problem so the next release should work. Since we again need some time to publish it, commenting the tools out (like you did) is a workaround.

**Comment by janbender** [comment]
That's a good point. I will add this in the next version.

**Comment by janbender** [comment]
In the current version the CMake flags for the tools are included.

**Comment by fabiocruz** [comment]
> In the current version the CMake flags for the tools are included.

Thank you @janbender for taking the suggestion and implementing it!
