### ISSUE TITLE
Tutorial, code usage examples

### ISSUE THREAD

**Issue by ManosAgelidis** [InteractiveComputerGraphics/SPlisHSPlasH#24]
Hello, is there maybe a plan to publish some tutorials on the usage of the library, setting up a minimal example, some code snippets to help users get started? Alternatively, any plans for a workshop on SPlisHSPlash?

**Comment by janbender** [comment]
Currently, there is no tutorial. But there are several example scene files and a doxygen documentation. 

Moreover, we will offer a SPH tutorial at Eurographics 2019 where SPlisHSPlasH will also be introduced.

**Comment by janbender** [comment]
We just added some documentation: 

https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/blob/master/doc/getting_started.md
https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/blob/master/doc/file_format.md

**Comment by ManosAgelidis** [comment]
Great, thanks!
