### ISSUE TITLE
A compile error and how to solve it

### ISSUE THREAD

**Issue by lyd405121** [InteractiveComputerGraphics/SPlisHSPlasH#241]
## A compile error
- lastest version, compile at 2023/4/26
- cmake default setting with VS2022
- here is the log
``` c
E:\linyaodong\SPlisHSPlasH\SPlisHSPlasH\Utilities\SceneParameterObjects.h(79,31): error C2079: “Utilities::FluidModelParameterObject::resolutionSDF”
```

## Why
- the std:;array header file is not right included
 
![array](https://user-images.githubusercontent.com/16344694/234470371-85f4915e-9b1c-4f40-b188-c4bf673a1b1c.png)

![include](https://user-images.githubusercontent.com/16344694/234470394-4b904b4b-fbcc-47dc-9e00-38a6f1996031.png)

## How to solve this
- simply add <array> in the begining
![solve](https://user-images.githubusercontent.com/16344694/234470547-01e08371-fbef-496e-918a-b8f359fca438.png)

**Comment by janbender** [comment]
Thanks for reporting this. I just tested on my system with VS 2022. However, I don't get any compiler error. 

I added the additional include so this should solve the problem on any system.

**Comment by lyd405121** [comment]
> 
- Thanks for your respond :)


> Thanks for reporting this. I just tested on my system with VS 2022. However, I don't get any compiler error.
> 
> I added the additional include so this should solve the problem on any system.
