### ISSUE TITLE
How to build a mesh based on particles

### ISSUE THREAD

**Issue by PavelBlend** [InteractiveComputerGraphics/SPlisHSPlasH#27]
How to build a mesh based on particles?
To get the output polygonal object, instead of particles.
What did you use to create meshes in these simulations?:
https://youtu.be/elZieJNBYqk

**Comment by janbender** [comment]
We use the emPolygonizer which is a tool that reconstructs the surface using a Marching Cubes method. However, the developer of this tool told me last week that we won't continue developing this tool and even took it offline.

**Comment by PavelBlend** [comment]
Are you planning to write your own polygonizer in the future?

**Comment by janbender** [comment]
Yes, we will definitely do this. However, this will take a while.
