### ISSUE TITLE
GPU porting / Performance improvements

### ISSUE THREAD

**Issue by ManosAgelidis** [InteractiveComputerGraphics/SPlisHSPlasH#28]
Hello, 

I have been using SPlisHSPlasH in interaction with the gazebo robotics simulator which is in turn interfacing with the ODE, bullet, SimBody physics engines. So far everything seems to be running well, but the simulation is quite slow, and the bottleneck is on the fluid simulation side. Do you have any tips on how I could try to accelerate the simulation (other than just using a more powerful machine), and more importantly, are there any plans to port SPlisHSPlasH to the GPU? If not, is there a specific reason for this? Maybe the simulation methods don't scale well on the GPU?

**Comment by janbender** [comment]
In general fluid simulation is quite time consuming. Mainly two parts are especially costly in SPH: the neighborhood search and the pressure solver. 

We already implemented a GPU neighborhood search and I hope that we can publish it in the next weeks. Moreover, we are working on an AVX acceleration of the pressure solver. 

In fact, SPH simulations work well on the GPU. However, we didn't had the time yet to implement a full GPU version.

**Comment by ManosAgelidis** [comment]
Thank you very much for the answer. Can I ask if there is a plan to port the pressure solver to the GPU, maybe within the next months? It would be a real advantage on top of the other SPH frameworks, as SPlisHSPlasH has all the state of the art SPH methods and the boundary handling method of Akinci et al, which makes easy to couple to rigid body dynamics solvers.
