### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by Domix93** [InteractiveComputerGraphics/SPlisHSPlasH#3]
Hello I have never used Cmake before. When I'm trying to compile, Cmake returns this error: 

CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/ExternalProject.cmake:1757 (message):
  error: could not find git for clone of
  ExternalProject_PositionBasedDynamics
Call Stack (most recent call first):
  C:/Program Files (x86)/CMake/share/cmake-3.5/Modules/ExternalProject.cmake:2459 (_ep_add_download_command)
  CMakeLists.txt:36 (ExternalProject_Add)

I'm using VS2015, Windows 10 64-bit and CMake 3.5.2.
Can anyone help me to solve this ?

**Comment by janbender** [comment]
When building SPlisHSPlasH, cmake tries to clone PositionBasedDynamics from Github. This is defined in the top CMakeLists.txt. I don't know why this doesn't work. Can you try to clone PositionBasedDynamics manually and see if this works?

**Comment by WeilerMarcel** [comment]
Hello Domix93, as the error message tells you, CMake can not find the git executable, which is required to download two additional libraries.
Do you have Git installed on your machine, or did you download our library as a .zip archive from GitHub? If you have Git installed, make sure it is added to your PATH variable. Alternatively you can set the GIT_EXECUTABLE variable in CMake to point to the location of git.exe. If this variable is hidden, make sure Advanced is checked in the CMake Gui.

**Comment by Domix93** [comment]
Hi, thank's for replies. I already solved this problem ;-). However, when the program is built and the simulation is enabled, it works very slow. How to make the simulation run smoothly ?

**Comment by WeilerMarcel** [comment]
Make sure you compile in Release mode and run the demo applications without debugger attached.
You can also set the '# time steps / update' in the GUI to 1, to update the rendered particles more frequently.

**Comment by Domix93** [comment]
WeilerMarcel, I am grateful for your help. Now it works fine.
