### ISSUE TITLE
Dynamic boundary demo fails with error

### ISSUE THREAD

**Issue by ManosAgelidis** [InteractiveComputerGraphics/SPlisHSPlasH#30]
The build is successful, after adding an entry in the CMakeLists that explicitly finds openMP, but when I try to run the DynamicBoundaryDemo it crashes with 

./DynamicBoundaryDemo 
Load scene file: /home/manos/Dev/spl/SPlisHSPlasH/data/Scenes/DoubleDamBreak.json
OpenGL version 4.6
Using GLEW 1.12.0
Vendor: NVIDIA Corporation
Renderer: GeForce GT 730M/PCIe/SSE2
Version: 4.6.0 NVIDIA 396.54
Load scene file: /home/manos/Dev/spl/SPlisHSPlasH/data/Scenes/DoubleDamBreak.json
DynamicBoundaryDemo: /home/manos/Dev/spl/SPlisHSPlasH/extern/json/json.hpp:927: void nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType>::assert_invariant() const [with ObjectType = std::map; ArrayType = std::vector; StringType = std::__cxx11::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator]: Assertion `m_type != value_t::array or m_value.array != nullptr' failed.
Aborted (core dumped) 

System : 
Ubuntu 16.04
gcc (Ubuntu 6.5.0-2ubuntu1~16.04) 6.5.0 20181026

**Comment by janbender** [comment]
I cannot reproduce this problem. I tested it on Debian 9 64-bit, CMake 3.12.3, GCC 6.3.0, where it works.

**Comment by ManosAgelidis** [comment]
I tried recloning the repo, and still I get the same error.  Maybe it is caused by these lines that I add in the CMakeLists of the Simulators folder 

FIND_PACKAGE( OpenMP)
  if(OPENMP_FOUND)
     message("OPENMP FOUND")
     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
     set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} ${OpenMP_EXE_LINKER_FLAGS}")
  endif()
 include_directories(SYSTEM ${OpenMP_INCLUDE_PATH})

Without these changes though gcc cannot find the OpenMP libraries. In any case thank you for looking into it, I will try to find a workaround.
