### ISSUE TITLE
Defining a Big geometry in one file and want from splishsplash to recognize all the parts

### ISSUE THREAD

**Issue by hosseinrezaa** [InteractiveComputerGraphics/SPlisHSPlasH#300]
Hello
I am simulating water particles between ice floes. I want to import the ice floes in one file but I want splishsplash code to behave all the ice floes seperately.

![image](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/assets/48132503/f245f6b9-b0a9-449f-876c-459471d78ba6)

I want the ice floes to react to the water particles separately. At the moment Splishsplash considers the whole domain like a solid geometry and when I apply a external force it will impose to the whole domain.

Is it possible to solve this problem?

Best Regards

**Comment by janbender** [comment]
This is not intended in SPlisHSPlasH as each "RigidBody" entry defines one rigid body. Either you define one rigid body per closed geometry part, which in your case might be unpractical, or I would recommend to use a Python script to define the scene. In this case you can simply loop over all geometry parts. However, you have to subdivide them.

**Comment by hosseinrezaa** [comment]
Thank you for your response.
I have another question. I want to make the ice floes dynamic but also I want constrain them to prevent in specific rotations.
How should I do that?

**Comment by janbender** [comment]
SPlisHSPlasH uses the PBD library to simulate dynamics rigid bodies. You could extend this library and implement a constraint which constrains the rotations.
