### ISSUE TITLE
Windows CMake issue

### ISSUE THREAD

**Issue by stapperfend** [InteractiveComputerGraphics/SPlisHSPlasH#306]
There is an error making SPlisHSPlasH following the [windows installation instruction: ](https://splishsplash.readthedocs.io/en/latest/build_from_source.html#installation-instructions-windows )

![CMAKE error](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/assets/49984969/0b5f9815-1166-4d4a-aae7-86e29bedb5b2)

I think this is an issue with never CMAKE versions. I am using CMake 3.29.0 as I want to use a current Visual Studio version. 
In the  ([GitHub Documentation](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH)) it is mentioned to use CMake 3.18.3 and ([readthedocs ](https://splishsplash.readthedocs.io/en/latest/py_getting_started.html)) suggests to go for CMake 3.13

**Comment by janbender** [comment]
This does not look like a CMake problem. It seems that CMake does not find the file AVX_math.h. Can you please take a look in the folder SPlisHSPlasH\Utilities if the file exists?

**Comment by stapperfend** [comment]
![image](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/assets/49984969/9ea40b02-87b9-4d83-bb92-65ff783c2a68)

Yes we double checked that the file exists. The subdirectory "Utilities" is also added in the main CMakeLists.txt file.

**Comment by janbender** [comment]
That's weird. If Desktop/SPlisHSPlasH is your root directory, the file should be in Desktop/SPlisHSPlasH/SPlisHSPlasH/Utilities and not in Desktop/SPlisHSPlasH/Utilities. How did you install the source files?
