### ISSUE TITLE
Implement rotating objects

### ISSUE THREAD

**Issue by rakueEP** [InteractiveComputerGraphics/SPlisHSPlasH#31]
You showed an impressive animation of a rotating dough hook (Eurographics 2018).
Could you please explain how to implement an object rotating with a fixed speed (the hook)?
Some example lines of code would be very helpful.

**Comment by janbender** [comment]
The hook is driven by three motors which are simulated using the PositionBasedDynamics library. You can simulate scenes like that by adding motor joints in the scene file and defining a target sequence for the motor.

This is from the original hook scene file (the spheres are used as dummy objects to link the hook with multiple motors): 

             "RigidBodies": [
		{
			"geometryFile": "../models/DoughHookCoarse.obj",
			"density": 0.000001,
			"translation": [0,3,0],
			"rotationAxis": [0, 0, 1],
			"rotationAngle": 0.261799,
			"scale": [10,10,10],
			"color": [0.7, 0.7, 0.72, 1.0], 
			"isDynamic": true,
			"isWall": false,
			"id": 0
		},
		{
			"geometryFile": "../models/sphere.obj",
			"density": 1,
			"translation": [0,3,0],
			"rotationAxis": [0, 0, 1],
			"rotationAngle": 0.0,
			"scale": [0.1,0.1,0.1],
			"color": [0.3, 0.0, 0.1, 1.0], 
			"isDynamic": true,
			"isWall": false,
			"id": 1
		},
		{
			"geometryFile": "../models/sphere.obj",
			"density": 100,
			"translation": [0,3,0],
			"rotationAxis": [0, 0, 1],
			"rotationAngle": 0.0,
			"scale": [0.1,0.1,0.1],
			"color": [0.3, 0.0, 0.1, 1.0], 
			"isDynamic": true,
			"isWall": false,
			"id": 2
		},
		{
			"geometryFile": "../models/DoughBowlLarge.obj",
			"translation": [0,0,0],
			"rotationAxis": [1, 0, 0],
			"rotationAngle": 0,
			"scale": [10,10,10],
			"color": [0.6, 0.55, 0.5, 1.0], 
			"isDynamic": false,
			"isWall": false,
			"id": 3
		}
	],
	"TargetVelocityMotorHingeJoints": [
		{
			"bodyID1": 2,
			"bodyID2": 1,
			"position": [0,3,0],
			"axis": [0,-1,0],
			"_target": -1.57079633,
			"targetSequence": [0,0, 4,0, 7,-0.785398163397448, 27,-0.785398163397448, 28,0],
			"repeatSequence": false
		},
		{
			"bodyID1": 1,
			"bodyID2": 0,
			"position": [0,3,0],
			"axis": [0.258819,-0.9659258,0],
			"_target": -7.85398163,
			"targetSequence": [0,0, 4,0, 7,-3.142, 27,-3.142, 28,0],
			"repeatSequence": false
		}
	],
	"TargetPositionMotorSliderJoints": [
		{
			"bodyID1": 3,
			"bodyID2": 2,
			"position": [0,3,0],
			"axis": [0,-1,0],
			"targetSequence": [0,0, 1.0,0, 4,3, 28,3, 31,0],
			"repeatSequence": false
		}
	]
