### ISSUE TITLE
MySPH does not work in pySPlisHSPlasH

### ISSUE THREAD

**Issue by happtain** [InteractiveComputerGraphics/SPlisHSPlasH#314]
Hello,
I rewrite DFSPH method and added some Fluid attributes, and I put the update to the new property in the step method of DFSPH. It could works well in the c++ version but does not work in the pySPlisHSPlasH, my new attribute does not change.

What should I do?

Best Regards

**Comment by digitalillusions** [comment]
If you change the C++ code you need to add the bindings to the new python property and then recompile the python package yourself. If you changed DFSPH you might need to add bindings here https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/blob/master/pySPlisHSPlasH/DFSPHModule.cpp .

If you have a functional C++ toolchain, you could build and install the new python package by calling `pip install .` in the root directory.

**Comment by happtain** [comment]
Thank you for your reply. I have solved this by add some bindings as your suggestion.
