### ISSUE TITLE
Build Error CuNSearch

### ISSUE THREAD

**Issue by Perpetual3134** [InteractiveComputerGraphics/SPlisHSPlasH#317]
Can anyone help with this error during building?

![grafik](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/assets/130981821/1982b8a2-d643-459f-b7e3-dbc660918528)

**Comment by janbender** [comment]
The tools do not support the use of cuNSearch. Just deactivate these tools in CMake and it should work.
