### ISSUE TITLE
VS Build Error

### ISSUE THREAD

**Issue by Perpetual3134** [InteractiveComputerGraphics/SPlisHSPlasH#319]
![grafik](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/assets/130981821/f1004bc6-529b-44fb-bc20-436d5926b8eb)

Compiling will not work... See attached image...

Please help!

**Comment by janbender** [comment]
The tools do not support the use of cuNSearch. Just deactivate these tools in CMake and it should work.

**Comment by Perpetual3134** [comment]
Thanks, furthermore i'm going to create my own exporter.
As a first step i try to duplicate the Partio exporter with renamed title.
I followed the steps in the documentation, but recive these errors: 
![grafik](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/assets/130981821/9e175ccd-9269-4ff2-9ab8-83689d236025)

I do not unterstand waths the problem here... 
Can you help?

**Comment by Perpetual3134** [comment]
![grafik](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/assets/130981821/14767f8a-8840-4170-8ac6-78f0a7a13c16)
