### ISSUE TITLE
OpenGL version available?

### ISSUE THREAD

**Issue by ghostplant** [InteractiveComputerGraphics/SPlisHSPlasH#32]
Is OpenGL version available to stream simulation output?

**Comment by janbender** [comment]
I do not understand your question.

**Comment by ghostplant** [comment]
I am expecting a simulation could be displayed with OpenGL or something for 3D realtime display.

**Comment by janbender** [comment]
As you can see on the screenshot, SPlisHSPlasH supports a direct OpenGL output.

**Comment by ghostplant** [comment]
I need an output target that run it with OpenGL, is it supported at the moment?
