### ISSUE TITLE
How do you consider foam when meshing the particles with marching cubes?

### ISSUE THREAD

**Issue by cesss** [InteractiveComputerGraphics/SPlisHSPlasH#34]
Hi!

I just built SPlisHSPlasH, and it's impressive! Anyway, I really need to mesh the particles, and, since you said in a closed issue that the marching cubes tool you used is no longer available, I might try to write my own. But there's one thing I don't know how to manage: foam. In your meshed videos, foam is rendered. How does the mesher detect foam from just the particles positions? And then, how does it generate a mesh that has foam? With a shader that has some scalar field for some color property? What shaders do you use for liquids and foam? Thanks!

**Comment by janbender** [comment]
The foam is generated by our foam generator tool. This is a post-processing step which generates foam particles that are then rendered as very small white spheres. You can read more about this in our paper "Turbulent Micropolar SPH Fluids with Foam". 

Currently, I cleanup the foam generator to publish it in the SPlisHSPlasH framework. However, this will take again some weeks.

**Comment by cesss** [comment]
Thanks a lot for your prompt reply. Yes, the foam generator would be one thing I was really looking for. In fact, seeing foam in the videos was the thing that made me choose SPlisHSPlasH as the first option for SPH simulation (I want to integrate an in-development 3D framework with _state of the art_ fluids simulation, so that the framework is designed in a way which is be able to communicate cleanly and efficiently with the simulation). 

So, I really wish to see the foam generator!! By the way, am I right assuming that the procedure that you followed for meshing the particles in the videos is just mesh them ignoring the foam, and then overlap small white spheres on top of the mesh? Did you also add spheres for the air bubbles? (In some videos it seems you can see something resembling bubbles inside the water, but it might be my imagination)

**Comment by janbender** [comment]
The foam generator adds foam, spray and bubble particles. In the end we import the mesh and the generated particles in Maya and render them together. So to answer your question, the mesh and the foam are independent from each other. 

The meshes were generated using emPolygonizer. However, unfortunately this nice tool is not online anymore.

**Comment by janbender** [comment]
Maybe I should also mention that we work currently on an own surface reconstruction tool for meshing but this will take a while until we can publish it.

**Comment by cesss** [comment]
Thanks a lot!! I really wish to see the foam generator soon!! Regarding the surface reconstruction, I might try it to write it myself, but I obviously look forward to see your implementation!!

**Comment by cesss** [comment]
Do particles have any value or tag for helping decide if they belong to the boundary or to the interior? I'm asking this because I found that Wenzel Jakob's [Instant Meshes](https://github.com/wjakob/instant-meshes) can mesh a point cloud, but reading the code I'm guessing it supports point clouds for the exterior surface, and not for volumes...

If it's easy to differentiate boundary particles from interior ones, then that mesher/remesher could be a great tool for meshing SPlisHSPlasH results...

**Comment by janbender** [comment]
There is no tag but there exist different methods to find the surface particles, e.g. by using a color field.


Am 28. Mai 2019 10:42:25 MESZ schrieb cesss <notifications@github.com>:
>Do particles have any value or tag for helping decide if they belong to
>the boundary or to the interior? I'm asking this because I found that
>Wenzel Jakob's [Instant
>Meshes](https://github.com/wjakob/instant-meshes) can mesh a point
>cloud, but reading the code I'm guessing it supports point clouds for
>the exterior surface, and not for volumes...
>
>If it's easy to differentiate boundary particles from interior ones,
>then that mesher/remesher could be a great tool for meshing
>SPlisHSPlasH results...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/issues/34#issuecomment-496422482

-- 
Diese Nachricht wurde von meinem Mobiltelefon gesendet.

**Comment by cesss** [comment]
How is the foam generator cleanup progressing? It will make this software shine!!

**Comment by cesss** [comment]
Thanks a lot for telling me. I really hope you can find some time not too far in the horizon!

**Comment by cesss** [comment]
I don't wish to add pressure (pun intended :-) but just wondering if there's any progress in the publishing of the foam generator :-)

BTW, regarding meshing, I believe VTK can mesh particles... maybe that's an option?

**Comment by janbender** [comment]
I started to cleanup the code and improved some things. However, then the next deadline came and I had to interrupt the cleanup. But it is still on my (long) todo list.

**Comment by janbender** [comment]
Okay, it took very long but now the foam generator is online.
