### ISSUE TITLE
How to run a scene with turbulence and vortex ?

### ISSUE THREAD

**Issue by 2080717101** [InteractiveComputerGraphics/SPlisHSPlasH#37]
Hello, 
I just built the project, it's really a big project, the paper and project are awesome. I'm a newcomer in sph, and I want to observe your effect in the vortex project. So I just changed the "m_sceneFile" in "SimulatorBase::init" function, from "DoubleDamBreak.json" to "CoilingModel_Bender2017.json". Then run the project. Like this.
![2](https://user-images.githubusercontent.com/18326271/60824212-c8c87180-a1db-11e9-98ee-fb8886e35f0d.PNG)
The result seems strange, like that. 
![1](https://user-images.githubusercontent.com/18326271/60824238-d3830680-a1db-11e9-87a0-b5ce591620b9.PNG)
I think I do something wrong. What other models or emitters do I need to prepare?
Thank you for your help.

**Comment by janbender** [comment]
Hi,

The scene file is a command line parameter, so you don't need to change the code. The Coiling example shows highly viscous material behavior. The obstacle example uses the micropolar turbulence model. The scene files can be easily modified.

Hope that helps!


Am 8. Juli 2019 17:59:08 MESZ schrieb 2080717101 <notifications@github.com>:

**Comment by 2080717101** [comment]
I think I know how to do. Thank you very much!!!!
