### ISSUE TITLE
Why the particles fly away but not rolling along the surface？

### ISSUE THREAD

**Issue by mingweiLIU** [InteractiveComputerGraphics/SPlisHSPlasH#38]
Hi, I am totally a newcomer to Fluid Simulation,  I built the project and generated the scene file based on the example of ViscousBunny expecting to see the particles rolling along the surface, while it comes out that particles were fly away as the image illustrates 
![pic1](https://user-images.githubusercontent.com/11702952/60980150-80898a80-a366-11e9-8e00-682c569f902c.jpg)
Is the configurations are not suitable for my case?
the scene files are in the attachment.
[scnee.zip](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/3378118/scnee.zip)

**Comment by janbender** [comment]
I just can guess what happened. The boundary viscosity is computed explicitely. Therefore, don't use high stiffness values in combination with large time steps. Maybe you could try to set it to zero. If that solves your problem, try it again with smaller stiffness values.

**Comment by janbender** [comment]
Otherwise you could try to decrease the CFL factor to get a lower time step size.

**Comment by mingweiLIU** [comment]
Thanks for the reply, I have tried both solutions while it still can't work.

**Comment by mingweiLIU** [comment]
One thing is that the parito file is generated by myself, does it matter?

**Comment by janbender** [comment]
I tried to view at the partio file with the PartioViewer but it does not show any particle nor a boundig box.

**Comment by mingweiLIU** [comment]
I am sorry for the particles are not around the center of the scene, actually, you may have to rotate around to make it visible
