### ISSUE TITLE
Is it easy to compute the previous frame from the current one?

### ISSUE THREAD

**Issue by cesss** [InteractiveComputerGraphics/SPlisHSPlasH#39]
Hi, I'm asking this question for SPlisHSPlasH, but I'm actually also interested in this question for your PositionBasedDynamics library as well.

Is it possible to run the simulation backwards instead of forward? I'm asking this because I'd like to be able to jump to any frame in the simulation without having to store all the positions for each frame (that would be overkill in memory consumption), and without having to run the simulation from the beginning every time.

If that's possible, I would add two arrows in my GUI: one arrow for "step backwards" and another for "step forward" (in addition to the play/pause button).

As I said, I'm interested in this question for PositionBasedDynamics as well.

Thanks!!

**Comment by janbender** [comment]
Hi, 

no that is not possible and I think inverse dynamics is a hard problem.
Storing the data is very simple and just requires some memory. Especially for PBD this shoudn't be a problem since not much memory is required.

**Comment by cesss** [comment]
I understand, Jan, thanks a lot for the clarification! Maybe for liquids it can be a bit costly to store all particles per-frame, but, if I manage to mesh the liquid, I think storing just the liquid surfaces per-frame won't take too much RAM.
