### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Domix93** [InteractiveComputerGraphics/SPlisHSPlasH#4]
Hello. Is it possible to replace AntTweakBar with windows forms, or it's not ?

**Comment by hai001** [comment]
Thank you for sharing the project, it's very useful for my research. I just have one question, when I  using CMake to compile the project(Windows 10 64-bit, CMake 3.8.1/3.5.2/3.2.1 Visual Studio 2015), it always has some trouble (screenshot), it seems that the PBD project has some problem. Looking forward for your answer, thank you again!
![splishsplash](https://cloud.githubusercontent.com/assets/24447496/25788703/ae6e710e-33dd-11e7-8cfc-0678596444c9.jpg)

**Comment by janbender** [comment]
You need to install git. Cmake needs it to install pbd.



Am 8. Mai 2017 05:01:57 MESZ schrieb Haijiang Li <notifications@github.com>:
>Thank you for sharing the project, it's very useful for my research. I
>just have one question, when I  using CMake to compile the
>project(Windows 10 64-bit, CMake 3.8.1/3.5.2/3.2.1 Visual Studio 2015),
>it always has some trouble (screenshot), it seems that the PBD project
>has some problem. Looking forward for your answer, thank you again!
>![splishsplash](https://cloud.githubusercontent.com/assets/24447496/25788703/ae6e710e-33dd-11e7-8cfc-0678596444c9.jpg)
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/issues/4#issuecomment-299761826

-- 
Diese Nachricht wurde von meinem Mobiltelefon gesendet.

**Comment by janbender** [comment]
Yes. Why not? The library SPlisHSPlasH is independent of the GUI. You just have to replace the Demos and write your own ones.
