### ISSUE TITLE
vtk export

### ISSUE THREAD

**Issue by dafue** [InteractiveComputerGraphics/SPlisHSPlasH#42]
Hello!
When I run a simulation with vtk export enabled, I just can see the particles made with fluid blocks in Paraview. Particles from an emitter are just represented by an single point in Paraview. This also happens, when I use partio2vtk.
In PartioViewer everything looks fine.

Best regards

**Comment by WeilerMarcel** [comment]
Hi,
I just tried it out with Emitter.json and MultiPhaseColoring.json. Exporting to vtk works fine for both scenes. Can you post your scene file?
Cheers,
Marcel

**Comment by janbender** [comment]
If you have two phases, you also have to import both phases in ParaView since each phase has its own file name. Maybe this was the problem.

**Comment by dafue** [comment]
Yes, I importet the vtk files for both phases in Paraview.
Today I exportet the vtk files from the MultiPhaseColoring scene in Paraview as csv files, to check if the files from the emitter are empty.
In the csv file I can see that, every point from the emitter phase got velocity and position data, but all points got the id "0". Points from the non emitter phase got all an non zero id, so maybe the id is the problem.
Here is the scene file for my testcase as txt:
[test.txt](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/3651863/test.txt)

**Comment by janbender** [comment]
Marcel fixed this. Now it should work.
