### ISSUE TITLE
Record or save simulations 

### ISSUE THREAD

**Issue by venkat-charan** [InteractiveComputerGraphics/SPlisHSPlasH#46]
Is there any way to save or record the simulations? As we did not find any option on the gui to do the same, we were wondering if there is an option in the code where this can be enabled.

**Comment by janbender** [comment]
In the GUI there are options for exporting partio, VTK and rigid body data. Partio contains all particle information and can be rendered by Maya, Blender or Houdini. You can also use the PartioViewer of the project to visualize the exported data. 

In the new version there is also an option to save a state of the simulation. A state contains everything and can be used to stop a simulation and continue later.
