### ISSUE TITLE
PartioViewer export bug in Linux

### ISSUE THREAD

**Issue by AimHere** [InteractiveComputerGraphics/SPlisHSPlasH#49]
On my Ubuntu 18.04 machine, the render to Video function of PartioViewer refuses to work with the '--renderVideo' option set, failing with the error 'Cannot open pipe to ffmpeg'.

Looking into it, the culprit seems to be in line 527 (or thereabouts) of ./Tools/PartioViewer/main.cpp, where the second argument of the popen library function is called with the invalid argument "wb" instead of just "w". Seems that the only [guarantees from the Open Group](https://pubs.opengroup.org/onlinepubs/009695399/functions/popen.html) are that 'r' and 'w' are supported and that anything else is undefined. The Linux [manpage](http://man7.org/linux/man-pages/man3/popen.3.html) only gives 'w' 'r' and an optional 'e' suffix

I fixed it by changing the offending line from
`if (!(ffmpegPipe = popen(sstm.str().c_str(), "wb")))`
to
`if (!(ffmpegPipe = popen(sstm.str().c_str(), "w")))`

in the fallback case, and I suspect that falling back to the guaranteed case in the spec is the Right Thing to do. If there's a non-WIN32 machine that uses the 'wb' type, it should probably be handled in another #elif clause.

**Comment by janbender** [comment]
Thanks for this solution. I will test it soon.

**Comment by janbender** [comment]
I just integrated your fix. Thx.
