### ISSUE TITLE
DFSPH Pressure and Divergence Solver are Identical?

### ISSUE THREAD

**Issue by ibchristensen** [InteractiveComputerGraphics/SPlisHSPlasH#5]
I was looking through TimeStepDFSPH::pressureSolve() and TimeStepDFSPH::divergenceSolve() and noticed that they calculate the exact same velocity delta. Looking at the paper it's based on I assumed there would be some differences. 

In pressureSolve it uses computeDensityAdv which calculates the exact same thing as computeDensityChange (which is used in divergenceSolve) without subtracting the rest density and a multiplication by the inverse step size. In pressureSolve anywhere it uses densityAdv it subtracts the rest density and multiplies by factor which includes the inverse step size. So the calculated values end up being the same unless I'm missing something. 

Relevant chunk of pressureSolve:

```
const unsigned int neighborIndex = m_model->getNeighbor(0, i, j);
const Real b_j = m_simulationData.getDensityAdv(neighborIndex) - density0;
const Real kj = b_j*m_simulationData.getFactor(neighborIndex);
const Real kSum = (ki + kj);
if (fabs(kSum) > m_eps)
{
	const Vector3r &xj = m_model->getPosition(0, neighborIndex);
	const Vector3r grad_p_j = -m_model->getMass(neighborIndex) * m_model->gradW(xi - xj);

	// Directly update velocities instead of storing pressure accelerations
	v_i -= h * kSum * grad_p_j;			// ki, kj already contain inverse density						
}
```

Relevant chunk of divergnceSolve:

```
const unsigned int neighborIndex = m_model->getNeighbor(0, i, j);					
const Real b_j = m_simulationData.getDensityAdv(neighborIndex);
const Real kj = b_j*m_simulationData.getFactor(neighborIndex);
const Real kSum = (ki + kj);
if (fabs(kSum) > m_eps)
{
	const Vector3r &xj = m_model->getPosition(0, neighborIndex);
	const Vector3r grad_p_j = -m_model->getMass(neighborIndex) * m_model->gradW(xi - xj);
	v_i -= h * kSum * grad_p_j;			// ki, kj already contain inverse density
}

```

(I also don't get how ki and kj contain inverse density, since their calculation doesn't use the density at all, but that's a different issue)

**Comment by janbender** [comment]
> In pressureSolve it uses computeDensityAdv which calculates the exact same thing as computeDensityChange 

That is not correct. computeDensityAdv computes the advected density, i.e. a preview of the density at time t+h (first equation in section 3.3). computeDensityChange  computes the divergence of the velocity field (equation 6 in the paper). So the first is a density and the second the density derived wrt. t.

The computation of the solvers is the same since the matrix on the left hand side is equal, only the right hand side of the linear system changes.

**Comment by ibchristensen** [comment]
In computeDensityAdv:

```
densityAdv = density + h*delta;
densityAdv = max(densityAdv, density0);
```
In computeDensityChange:

```
densityAdv = density + h*densityAdv;
densityAdv = max(densityAdv, density0);
densityAdv = (densityAdv - density0) * (1.0 / h);
```

The value of delta and densityAdv are calculated exactly the same in both functions so the only difference is the last line in computeDensityChange. Looking at how the final value is used in pressureSolve (which uses computeDensityAdv):
```
const Real b_i = m_simulationData.getDensityAdv(i) - density0;
const Real ki = b_i*m_simulationData.getFactor(i);
```
And how factor is adjusted for the pressureSolve:
`m_simulationData.getFactor(i) *= invH2;`
vs how factor is adjusted for the divergenceSolve:
`m_simulationData.getFactor(i) *= invH;`
(this gets multiplied back out at the end of the divergenceSolve to reset the factor)
k_i  ends up being the same value for both solvers.

**Comment by janbender** [comment]
Maybe there is a bug in the open-source implementation. I will check this. Unfortunately, this will take a while since currently I have not much time for the maintainance of the open-source libraries.
