### ISSUE TITLE
Rigid bodies in paraview

### ISSUE THREAD

**Issue by rakueEP** [InteractiveComputerGraphics/SPlisHSPlasH#50]
Hello,

i try to analyse some simulation results with rigid bodies in paraview.
The export (and import) of VTK files for the particles works fine.
How do handle the rigid bodies?
I'm not able to import the binary files in the rigid_bodies folder into paraview (file format?).
Is there a feature to also export this data into VTK file format?

Best,
Ralf

**Comment by janbender** [comment]
Currently, there is no VTK export of rigid bodies yet. The bin file format is an own format which is just used to export the data to the PartioViewer or Maya. But I agree that the rigid body export would be an important feature and will put it on our ToDo list.

**Comment by janbender** [comment]
The VTK rigid body export is implemented and will be included in the next version. I just need a bit time for testing other new features.

**Comment by rakue** [comment]
resolved #50
