### ISSUE TITLE
Very sensitive movement in 3D space

### ISSUE THREAD

**Issue by PavelBlend** [InteractiveComputerGraphics/SPlisHSPlasH#51]
It was more convenient if the sensitivity of camera movement in 3D space was lower. When I pull Shift and LMB, the camera in 3D space moves very quickly. Need to make moving slower.

**Comment by janbender** [comment]
Take a look in Visualization/MiniGL.cpp and adapt the values for movespeed and/or turnspeed.

**Comment by PavelBlend** [comment]
Maybe take out the navigation options in a separate json file?
Because it is not convenient to recompile for these settings.
