### ISSUE TITLE
Could NOT find GLUT (missing: GLUT_glut_LIBRARY GLUT_INCLUDE_DIR)

### ISSUE THREAD

**Issue by watersky803** [InteractiveComputerGraphics/SPlisHSPlasH#54]
Hi, I am interested in this project but I am not familiar with CMake. when I compiled the code with CMake in Ubuntu, I got the error message as follows.

The C compiler identification is GNU 5.4.0
The CXX compiler identification is GNU 5.4.0
Check for working C compiler: /usr/bin/cc
Check for working C compiler: /usr/bin/cc -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /usr/bin/c++
Check for working CXX compiler: /usr/bin/c++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Found OpenMP_C: -fopenmp (found version "4.0") 
Found OpenMP_CXX: -fopenmp (found version "4.0") 
Found OpenMP: TRUE (found version "4.0")  
Build type: 
CMake Error at /home/huali/Desktop/cmake-3.16.4-Linux-x86_64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find GLUT (missing: GLUT_glut_LIBRARY GLUT_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/huali/Desktop/cmake-3.16.4-Linux-x86_64/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  /home/huali/Desktop/cmake-3.16.4-Linux-x86_64/share/cmake-3.16/Modules/FindGLUT.cmake:130 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  Simulators/DynamicBoundarySimulator/CMakeLists.txt:9 (find_package)

Configuring incomplete, errors occurred!
it seems that it can't find the GLUT. I think it should install GLUT automatically rather than I install by hand. Could you tell me what I should do? thank you.

**Comment by janbender** [comment]
Is GLUT installed on your system?

**Comment by watersky803** [comment]
After  I installed the GLUT, it can be configured and generated, but when I used Make to compile the makefile. there are a lot of errors as follows. could you help me figure out where I need to pay attention? how to deal with those errors? thank you. My system is ubuntu 16.04 64 bits.  CMAKE 3.16.4 64 bits.
huali@ubuntu:~/Desktop/SPlisHSPlasH-master$ ls
bin            CMakeLists.txt  extern     Scripts       Tools
build          data            lib        Simulators    Utilities
Changelog.txt  doc             LICENSE    SPlisHSPlasH  Visualization
CMake          Doxyfile        README.md  Tests
huali@ubuntu:~/Desktop/SPlisHSPlasH-master$ cd build/
huali@ubuntu:~/Desktop/SPlisHSPlasH-master/build$ ls
CMakeCache.txt  cmake_install.cmake  Makefile    SPlisHSPlasH  Tools
CMakeFiles      extern               Simulators  Tests         Utilities
huali@ubuntu:~/Desktop/SPlisHSPlasH-master/build$ make
Scanning dependencies of target Ext_NeighborhoodSearch
[  1%] Creating directories for 'Ext_NeighborhoodSearch'
[  1%] Performing download step (git clone) for 'Ext_NeighborhoodSearch'
Cloning into 'Ext_NeighborhoodSearch'...
Note: checking out 'daf73f4d321ea3cfbdc88d23f56d8aaa0083479a'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at daf73f4... - added query function for single point x
[  1%] No patch step for 'Ext_NeighborhoodSearch'
[  2%] Performing update step for 'Ext_NeighborhoodSearch'
[  3%] Performing configure step for 'Ext_NeighborhoodSearch'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/huali/Desktop/SPlisHSPlasH-master/extern/CompactNSearch/src/Ext_NeighborhoodSearch-build
[  4%] Performing build step for 'Ext_NeighborhoodSearch'
Scanning dependencies of target CompactNSearch
[ 25%] Building CXX object CMakeFiles/CompactNSearch.dir/src/CompactNSearch.cpp.o
[ 50%] Linking CXX static library libCompactNSearch.a
[ 50%] Built target CompactNSearch
Scanning dependencies of target Demo
[ 75%] Building CXX object demo/CMakeFiles/Demo.dir/main.cpp.o
[100%] Linking CXX executable Demo
[100%] Built target Demo
[  5%] Performing install step for 'Ext_NeighborhoodSearch'
[ 50%] Built target CompactNSearch
[100%] Built target Demo
Install the project...
-- Install configuration: ""
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/NeighborhoodSearch/include/CompactNSearch
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/NeighborhoodSearch/include/Config.h
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/NeighborhoodSearch/include/CompactNSearch.h
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/NeighborhoodSearch/include/PointSet.h
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/NeighborhoodSearch/include/DataStructures.h
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/NeighborhoodSearch/lib/libCompactNSearch.a
[  5%] Completed 'Ext_NeighborhoodSearch'
[  5%] Built target Ext_NeighborhoodSearch
Scanning dependencies of target Ext_PBD
[  5%] Creating directories for 'Ext_PBD'
[  6%] Performing download step (git clone) for 'Ext_PBD'
Cloning into 'Ext_PBD'...
Note: checking out 'dd185b0a0479248cb0c1e98294532b55cb0d287d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at dd185b0... - fixed Eigen alignment
[  7%] No patch step for 'Ext_PBD'
[  7%] Performing update step for 'Ext_PBD'
[  8%] Performing configure step for 'Ext_PBD'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Build type: Release
-- Found Eigen3: /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/extern/eigen (Required is at least version "2.91.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD-build
[  8%] Performing build step for 'Ext_PBD'
Scanning dependencies of target Ext_GenericParameters
[  2%] Creating directories for 'Ext_GenericParameters'
[  4%] Performing download step (git clone) for 'Ext_GenericParameters'
Cloning into 'Ext_GenericParameters'...
Note: checking out 'b1ad669fac8d106515f6aa8514a03598d5766a36'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at b1ad669... - added function to clear enum values
[  6%] No patch step for 'Ext_GenericParameters'
[  8%] Performing update step for 'Ext_GenericParameters'
[ 10%] Performing configure step for 'Ext_GenericParameters'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/GenericParameters/src/Ext_GenericParameters-build
[ 12%] Performing build step for 'Ext_GenericParameters'
[ 14%] Performing install step for 'Ext_GenericParameters'
Install the project...
-- Install configuration: "Release"
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/GenericParameters/include
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/GenericParameters/include/ParameterObject.h
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/GenericParameters/include/NumericParameter.h
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/GenericParameters/include/Parameter.h
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/GenericParameters/include/EnumParameter.h
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/GenericParameters/include/VectorParameter.h
[ 17%] Completed 'Ext_GenericParameters'
[ 17%] Built target Ext_GenericParameters
Scanning dependencies of target Ext_Discregrid
[ 19%] Creating directories for 'Ext_Discregrid'
[ 21%] Performing download step (git clone) for 'Ext_Discregrid'
Cloning into 'Ext_Discregrid'...
Note: checking out 'c0fb5aeac4c8a83e9f37c720315f13a834409b81'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c0fb5ae... - make it compile with C++11
[ 23%] No patch step for 'Ext_Discregrid'
[ 25%] Performing update step for 'Ext_Discregrid'
[ 27%] Performing configure step for 'Ext_Discregrid'
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Found OpenMP: TRUE (found version "4.0")  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/src/Ext_Discregrid-build
[ 29%] Performing build step for 'Ext_Discregrid'
Scanning dependencies of target Discregrid
[ 10%] Building CXX object discregrid/CMakeFiles/Discregrid.dir/src/discrete_grid.cpp.o
[ 20%] Building CXX object discregrid/CMakeFiles/Discregrid.dir/src/cubic_lagrange_discrete_grid.cpp.o
[ 30%] Building CXX object discregrid/CMakeFiles/Discregrid.dir/src/acceleration/bounding_sphere_hierarchy.cpp.o
[ 40%] Building CXX object discregrid/CMakeFiles/Discregrid.dir/src/mesh/entity_containers.cpp.o
[ 50%] Building CXX object discregrid/CMakeFiles/Discregrid.dir/src/mesh/entity_iterators.cpp.o
[ 60%] Building CXX object discregrid/CMakeFiles/Discregrid.dir/src/mesh/triangle_mesh.cpp.o
[ 70%] Building CXX object discregrid/CMakeFiles/Discregrid.dir/src/geometry/mesh_distance.cpp.o
[ 80%] Building CXX object discregrid/CMakeFiles/Discregrid.dir/src/geometry/point_triangle_distance.cpp.o
[ 90%] Building CXX object discregrid/CMakeFiles/Discregrid.dir/src/utility/timing.cpp.o
[100%] Linking CXX static library ../bin/libDiscregrid.a
[100%] Built target Discregrid
[ 31%] Performing install step for 'Ext_Discregrid'
[100%] Built target Discregrid
Install the project...
-- Install configuration: "Release"
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/lib/libDiscregrid.a
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/geometry
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/geometry/mesh_distance.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/utility
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/utility/lru_cache.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/utility/serialize.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/discrete_grid.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/acceleration
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/acceleration/bounding_sphere.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/acceleration/kd_tree.inl
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/acceleration/kd_tree.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/acceleration/bounding_sphere_hierarchy.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/mesh
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/mesh/entity_iterators.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/mesh/triangle_mesh.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/mesh/halfedge.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/mesh/entity_containers.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/cubic_lagrange_discrete_grid.hpp
-- Installing: /home/huali/Desktop/SPlisHSPlasH-master/extern/install/Discregrid/./include/Discregrid/All
[ 34%] Completed 'Ext_Discregrid'
[ 34%] Built target Ext_Discregrid
Scanning dependencies of target PositionBasedDynamics
[ 36%] Building CXX object PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/MathFunctions.cpp.o
[ 38%] Building CXX object PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/PositionBasedDynamics.cpp.o
[ 40%] Building CXX object PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/PositionBasedElasticRods.cpp.o
/home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp: In static member function ‘static Real PBD::DirectPositionBasedSolverForStiffRods::factor(int, const std::vector<PBD::RodConstraint*>&, std::vector<PBD::RodSegment*>&, const PBD::Interval*&, std::__cxx11::list<PBD::Node*>*, std::__cxx11::list<PBD::Node*>*, std::vector<Eigen::Matrix<double, 6, 1, 2> >&, std::vector<Eigen::Matrix<double, 6, 1, 2> >&, std::vector<std::vector<Eigen::Matrix<double, 3, 3, 2> > >&)’:
/home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:778:45: error: no matching function for call to ‘max(Real&, int)’
    maxError = std::max(maxError, abs(rhs[i]));
                                             ^
In file included from /usr/include/c++/5/bits/char_traits.h:39:0,
                 from /usr/include/c++/5/ios:40,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/sstream:38,
                 from /usr/include/c++/5/complex:45,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/extern/eigen/Eigen/Core:80,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/extern/eigen/Eigen/Dense:1,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.h:4,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:1:
/usr/include/c++/5/bits/stl_algobase.h:219:5: note: candidate: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/5/bits/stl_algobase.h:219:5: note:   template argument deduction/substitution failed:
/home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:778:45: note:   deduced conflicting types for parameter ‘const _Tp’ (‘double’ and ‘int’)
    maxError = std::max(maxError, abs(rhs[i]));
                                             ^
In file included from /usr/include/c++/5/bits/char_traits.h:39:0,
                 from /usr/include/c++/5/ios:40,
                 from /usr/include/c++/5/istream:38,
                 from /usr/include/c++/5/sstream:38,
                 from /usr/include/c++/5/complex:45,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/extern/eigen/Eigen/Core:80,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/extern/eigen/Eigen/Dense:1,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.h:4,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:1:
/usr/include/c++/5/bits/stl_algobase.h:265:5: note: candidate: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/5/bits/stl_algobase.h:265:5: note:   template argument deduction/substitution failed:
/home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:778:45: note:   deduced conflicting types for parameter ‘const _Tp’ (‘double’ and ‘int’)
    maxError = std::max(maxError, abs(rhs[i]));
                                             ^
In file included from /usr/include/c++/5/algorithm:62:0,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/extern/eigen/Eigen/Core:269,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/extern/eigen/Eigen/Dense:1,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.h:4,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:1:
/usr/include/c++/5/bits/stl_algo.h:3457:5: note: candidate: template<class _Tp> _Tp std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^
/usr/include/c++/5/bits/stl_algo.h:3457:5: note:   template argument deduction/substitution failed:
/home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:778:45: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘double’
    maxError = std::max(maxError, abs(rhs[i]));
                                             ^
In file included from /usr/include/c++/5/algorithm:62:0,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/extern/eigen/Eigen/Core:269,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/extern/eigen/Eigen/Dense:1,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.h:4,
                 from /home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:1:
/usr/include/c++/5/bits/stl_algo.h:3463:5: note: candidate: template<class _Tp, class _Compare> _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/5/bits/stl_algo.h:3463:5: note:   template argument deduction/substitution failed:
/home/huali/Desktop/SPlisHSPlasH-master/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:778:45: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘double’
    maxError = std::max(maxError, abs(rhs[i]));
                                             ^
PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/build.make:88: recipe for target 'PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/PositionBasedElasticRods.cpp.o' failed
make[5]: *** [PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/PositionBasedElasticRods.cpp.o] Error 1
CMakeFiles/Makefile2:193: recipe for target 'PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/all' failed
make[4]: *** [PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/Ext_PBD.dir/build.make:111: recipe for target '../extern/PositionBasedDynamics/src/Ext_PBD-stamp/Ext_PBD-build' failed
make[2]: *** [../extern/PositionBasedDynamics/src/Ext_PBD-stamp/Ext_PBD-build] Error 2
CMakeFiles/Makefile2:494: recipe for target 'CMakeFiles/Ext_PBD.dir/all' failed
make[1]: *** [CMakeFiles/Ext_PBD.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ankurhanda** [comment]
@watersky803 did you figure out how to fix the issue to do with 
```
PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/build.make:105: recipe for target 'PositionBasedDynamics/CMakeFiles/PositionBasedDynamics.dir/PositionBasedElasticRods.cpp.o' failed
```
I'm getting this error too. I do have GLUT here `/usr/lib/x86_64-linux-gnu/libglut.so`

**Comment by ankurhanda** [comment]
OK -- so this is the fix 

```
SPlisHSPlasH/build/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:778:45: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘float’
    maxError = std::max(maxError, abs(rhs[i]));
```

In this file the `abs(rhs[i])` should be replaced with `(float)abs(rhs[i])`

**Comment by janbender** [comment]
Can you tell me on which system you are compiling the code and which settings did you use in CMake?

**Comment by ankurhanda** [comment]
```
Linux allegro 4.15.0-88-generic #88~16.04.1-Ubuntu SMP Wed Feb 12 04:19:15 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I didn't change CMake at all. 

Thank you.

**Comment by watersky803** [comment]
> OK -- so this is the fix
> 
> ```
> SPlisHSPlasH/build/extern/PositionBasedDynamics/src/Ext_PBD/PositionBasedDynamics/PositionBasedElasticRods.cpp:778:45: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘float’
>     maxError = std::max(maxError, abs(rhs[i]));
> ```
> 
> In this file the `abs(rhs[i])` should be replaced with `(float)abs(rhs[i])`

Thanks

**Comment by janbender** [comment]
I just checked the code. rhs[i] is already a float. So I wonder why abs does not return a float. Can you try to use the following code on your system:

maxError = std::max(maxError, fabs(rhs[i]));

**Comment by codylico** [comment]
Maybe that call to `abs(rhs[i])` should be a call to `std::abs(rhs[i])`? The first one may be referencing the C library version that only takes `int`.

**Comment by janbender** [comment]
I fixed that. Could you please try again with the udated version?

**Comment by codylico** [comment]
I tested the updated version. It successfully compiles on Ubuntu 18 using CMake.
