### ISSUE TITLE
can't compile in ubuntu 18.04 It warns "always_inline function might not be inlinable"

### ISSUE THREAD

**Issue by watersky803** [InteractiveComputerGraphics/SPlisHSPlasH#55]
I try to compile the code in ubuntu 18.04 in virtual machine on my Mac. I use g++7.4 gcc7.4 make4.1  cmake 3.16 . when I use Make to compile, many warning  is about always_inline function might not be inlinable. besides,it shows "PBD-DATA-PATH" redefined when bulld target DynamicBoundarysimulator. In the end,
90% Linking Cxx executable../../../bin/DynamicBoundaySimulator.
93% Linking Cxx executable../../../bin/StaticBoundaySimulator.
96% Linking Cxx executable../../../bin/PartioViewer.
97% Linking Cxx executable../../../bin/SurfaceSampling
98% Linking Cxx executable../../../bin/VolumeSampling
99% Linking Cxx executable../../../bin/partio2vtk
100% Linking Cxx executable../../../bin/KernelTests

I am not sure that if the warning"always-inline function might not be inlinable" is the main issue. the library can't be complied fully. and The executable link aren't be built totally. could you help me figure out how to fix it? it seems that it's close to the success. Thank you.

**Comment by janbender** [comment]
The warnings are no problem. Each compiler throws different warnings. However, it seems that everything builds correctly since all executables were linked. So you should be able to start them in the bin folder.

**Comment by watersky803** [comment]
when I click the DynamicBoundaySimulator or StaticBoundaySimulator, it tells me   "could not display "DynamicBoundaySimulator/StaticBoundaySimulator". there is no application installed for "shared library "files. Do you want to search for an application to open this file? "  then I check the permissions in the properties. it shows that Allow executing file as program.   which one application I need to install to run the executables?  or  I can't run it because most of the executables aren't 100% linked. thank you very much.

**Comment by watersky803** [comment]
it seems that I can't run it by clicking the executable in the bin folder. but I can run it via the Terminal. Thank you for your time and patience.
