### ISSUE TITLE
AVX support breaks the executables on older CPUs

### ISSUE THREAD

**Issue by ManosAgelidis** [InteractiveComputerGraphics/SPlisHSPlasH#58]
Hi,

This is not exactly an issue as it might be already known, but still worth reporting. In older CPUs the fact that the AVX support is enabled by default causes the code to build successfully but during running it fails with a cryptic messasge. After debugging it was made clear that the USE_AVX cmake option which is enabled by default causes the program to crash. Building with this opition off works fine. Maybe there is a way to check first if the AVX support is provided by the CPU and then setting the variable. Nevertheless maybe it is worth reporting in case someone has the same problem. 

Best,
Manos

**Comment by janbender** [comment]
Good point. We will try to check the AVX support.
