### ISSUE TITLE
Requesting changelog on Simulator changes

### ISSUE THREAD

**Issue by mskr** [InteractiveComputerGraphics/SPlisHSPlasH#59]
Hey, it is great that the library is actively supported. But there have been major changes to the project structure that I cannot understand. There were Static- and DynamicBoundarySimulators and now there is just an SPHSimulator. Does that mean, that it will switch between static and dynamic based on scene file, or is there no distinction anymore at all? I cannot really make sense of the commit message in 1b1f18ca30cd94e8ca628e6874a123693a332729.

**Comment by digitalillusions** [comment]
Hey, thanks for the suggestion. As far as I know, that is exactly the case. As soon as one dynamic boundary object is present in the scene file, the dynamic simulator will be used. See https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/blob/533dd3fd13564802e07bb32269ad75f4bc297d2e/Simulator/SimulatorBase.cpp#L338-L360
We're in the process of generating more and more user documentation with upcoming releases, especially with regard to the newly implemented python interface. However, as this is an active research project, the documentation will most likely never be complete or fully up to date, as we change things internally to fit our current needs. I hope this could help you out for the moment. I will keep this issue open so we might address it specifically in the future.

**Comment by janbender** [comment]
Yes, the SPHSimulator decides automatically. For only static boundaries the step for the rigid body simulator is skipped.

**Comment by mskr** [comment]
Thanks I like that new way.
