### ISSUE TITLE
Realtime?

### ISSUE THREAD

**Issue by BluePrintRandom** [InteractiveComputerGraphics/SPlisHSPlasH#6]
is there any chance to integrate a fluid solver like this into blender game engine fork - upbge?

BF_blender?

**Comment by WeilerMarcel** [comment]
If a simulation runs in real-time mainly depends on the complexity of your scene and the power of your computer. I doubt that you will be able to run simulations with more than a few thousand particles if your PC also has to do other stuff like updating game logic and rendering.

Regarding the implementation: I do not know the internals of Blender's Game Engine, but if I remember correctly it does not support particle systems. So implementing a particle system should be your fist concern. Porting the actual simulation should be pretty straightforward.
