### ISSUE TITLE
VolumeSampling WARNING: Mesh not closed!

### ISSUE THREAD

**Issue by mskr** [InteractiveComputerGraphics/SPlisHSPlasH#60]
I exported OBJ from solid modeling software (ANSYS SpaceClaim) and tried to VolumeSample it.

I get the warning and wrong output:

![1](https://user-images.githubusercontent.com/10597783/77776093-c77ef380-704d-11ea-95fa-10b512279d59.png)

OBJ looks like this:

![2](https://user-images.githubusercontent.com/10597783/77776128-d1a0f200-704d-11ea-8790-3e3a73effc64.png)

I verified the solidity of the OBJ by re-importing it to SpaceClaim and doing a repair:

![image](https://user-images.githubusercontent.com/10597783/77775973-9a324580-704d-11ea-9297-ed0a147e956a.png)

I will try to find the specific piece of code that is failing here.

**Comment by janbender** [comment]
The volume sample can sample one closed geometry. It seems that your geometry consists of two parts. Maybe you could sample them separately.

**Comment by mskr** [comment]
Sorry it may have looked like it but the geometry is actually connected. It is a pipe with a narrowing. Here is how it looks from the inside:

![image](https://user-images.githubusercontent.com/10597783/77777214-8687de80-704f-11ea-92e5-680858cf7dc6.png)

**Comment by janbender** [comment]
Is this a pure triangle mesh or are there also quads?

**Comment by mskr** [comment]
Verified that it is pure triangle by re-exporting from Blender with Triangulate Faces option.

**Comment by mskr** [comment]
Warning comes from Discregrid.

`VolumeSampling::sampleMesh() -> SDFFunctions::generateSDF()` -> `TriangleMesh::TriangleMesh()` ->
https://github.com/InteractiveComputerGraphics/Discregrid/blob/0b69062ff9c56fbb6dcecd296652028bedbacf0e/discregrid/src/mesh/triangle_mesh.cpp#L150-L187

Hard to say if this subroutine works correctly, esp. why it expects the set of half edges to be non-empty.

```c++
// Build adjacencies for mesh faces.
FaceSet face_set(
	(m_faces.size() * 3) / 2,
	HalfedgeHasher(m_faces),
	HalfedgeEqualTo(m_faces));
for (unsigned int i(0); i < m_faces.size(); ++i)
	for (unsigned char j(0); j < 3; ++j)
	{ ... }
...
for (Halfedge const he : face_set)
{
	m_b2e.push_back(he);
}
...
if (!m_b2e.empty())
{
	std::cout << std::endl << "WARNING: Mesh not closed!" << std::endl;
}
```

I will let it be for now and do some workaround.

**Comment by janbender** [comment]
Can you send me the mesh file? Maybe there are some unconnected parts.

**Comment by mskr** [comment]
Thanks for the help and no problem, you can do whatever you want with it :)
Here's the zipped OBJ:
[Fluid.zip](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/4399587/Fluid.zip)

**Comment by janbender** [comment]
By analyzing the mesh I can see that it has 8 boundaries. A closed mesh should have 0. The reason for this is that e.g. on the top and bottom disk there are duplicated vertices.

**Comment by mskr** [comment]
Ok not sure if I understand. But will try optimizing my geometry.

**Comment by mskr** [comment]
This fixed it:

![Blender-Mesh-Closing](https://user-images.githubusercontent.com/10597783/77909400-92f97a80-728d-11ea-88af-5bdc8edf91d4.png)
