### ISSUE TITLE
GPU error with cuNSearch for neighborhood search

### ISSUE THREAD

**Issue by kocmocgim** [InteractiveComputerGraphics/SPlisHSPlasH#62]
Windows 10. 64 bit. MSVS 15 2017. CMake 3.11.2. Configure
![2020-03-28_14-18-49](https://user-images.githubusercontent.com/24375347/77819750-12a50f00-70ff-11ea-8df5-9011c55ad107.png). 
![2020-03-28_14-21-36](https://user-images.githubusercontent.com/24375347/77819792-79c2c380-70ff-11ea-923c-633748354569.png)

generate without errors

compile project
![2020-03-28_14-26-57](https://user-images.githubusercontent.com/24375347/77819986-d7a3db00-7100-11ea-8767-a6cb2b3e2374.png)
can not find cuNSearch.h... so set full path
![2020-03-28_14-27-52](https://user-images.githubusercontent.com/24375347/77819988-da063500-7100-11ea-9648-d09641240486.png)
![2020-03-28_14-28-52](https://user-images.githubusercontent.com/24375347/77819990-db376200-7100-11ea-93d0-57f65c31818f.png)
1 error MSB6006 with cmd.exe 
6 error with "couldn't open cuNSearch_d.lib". There isn't the file.

All work without GPU neighborhood search

**Comment by janbender** [comment]
Can you try to build the release version?

**Comment by kocmocgim** [comment]
Reinstall VS 2017 and CMake. So i get "No CUDA toolset found" both in master and release
but CUDA compiler is still in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin

**Comment by kocmocgim** [comment]
I fixed "No CUDA toolset found" and compilation errors. Problem with integrating the CUDA toolkit with VS 2017. It is important to install the Cuda toolkit AFTER Visual Studio 2017. Cmake - VS 2017 - Cuda toolkit. This sequence.

but have next problem both in master and release:
![2020-03-29_02-27-10 (2)](https://user-images.githubusercontent.com/24375347/77834226-e7eda180-7164-11ea-9b33-ac775ed0db54.png)

**Comment by janbender** [comment]
Did you build a 64 bit version?

**Comment by janbender** [comment]
Btw. I would recommend building the release version since the debug version is built without optimization and is very slow.

**Comment by kocmocgim** [comment]
Yes, i build 64 bit version. 32 bit one is not configure.
Thank you for recommendation. That's why I started trying to run the GPU, since debug version is very slow now. Although Python bindings works very well.
