### ISSUE TITLE
Installation Issue in Ubuntu

### ISSUE THREAD

**Issue by alex-wy** [InteractiveComputerGraphics/SPlisHSPlasH#63]
After I cloned the repository, I skiped these code cuz "sjeske" doesn't exist in this repo.
```
git checkout sjeske/pybind
git pull
```
But when I wanted to install the **SPlisHSPlasH**, I got these error messages.
```
Processing ./SPlisHSPlasH
Building wheels for collected packages: pysplash
  Building wheel for pysplash (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/wuyue/anaconda3/envs/venv/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-uh0i7dfz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-uh0i7dfz/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mbp177al
       cwd: /tmp/pip-req-build-uh0i7dfz/
  Complete output (554 lines):
...
```
I tried the instructions in issue https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/issues/61 but it cannot work for me.

**Comment by digitalillusions** [comment]
We are in the process of updating documentation. Also the python package should now be available on Windows and Linux if you run 
```
pip install pysplishsplash
```
Additionally, please try to build the pysplishsplash target from the cmake project if you are getting issues with installing the python package. Debugging the building process can be a lot easier when working with cmake directly.
