### ISSUE TITLE
"illegal instruction (core dumped)" running all demos

### ISSUE THREAD

**Issue by aibel18** [InteractiveComputerGraphics/SPlisHSPlasH#66]
Configure the project with CMake 3.10.2, and compile with make 4.1 and gcc (Ubuntu 7.5.0-3ubuntu1 ~ 18.04) 7.5.0, and when I try to run the demos I get the following error:
> ./SPHSimulator
> Illegal instruction (core dumped)

**Comment by digitalillusions** [comment]
This might be an AVX issue. Try to reconfigure the project with `-DUSE_AVX=Off` and build afterwards. You may have to do a complete reconfigure (delete `CMakeCache.txt`) for this to work.

**Comment by aibel18** [comment]
Good, I compiled the program again and the error was solved, but I still do not see the demos now I get this error:
> ./SPHSimulator ../data/Scenes/DamBreakModel.json
> Initialize dynamic boundary simulation
Initialize fluid particles
Number of fluid particles: 5054
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  48
  Current serial number in output stream:  47
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  47
  Current serial number in output stream:  48

**Comment by janbender** [comment]
Seems to be an OpenGL issue. Can you run other OpenGL applications?
