### ISSUE TITLE
Dynamic objects behave incorrectly when an emitter is in the scene

### ISSUE THREAD

**Issue by harveybia** [InteractiveComputerGraphics/SPlisHSPlasH#67]
I tried to combine dynamic objects and emitters in the same file and could not get it to work properly.

Add an emitter to the example "MotorScene.json", and the dynamic motor blade starts to free fall without being constrained by the `TargetVelocityMotorHingeJoints`.

Correct behavior with only dynamic objects:
![image](https://user-images.githubusercontent.com/8027401/79311555-9dda1f00-7ecb-11ea-9970-bb2f731867e9.png)

Incorrect behavior when combined with an emitter:
![image](https://user-images.githubusercontent.com/8027401/79311826-fd382f00-7ecb-11ea-92ef-4db058f01869.png)

**Comment by harveybia** [comment]
Attached is my modified json file:

```json
{
	"Configuration": 
	{
		"particleRadius": 0.025,
		"numberOfStepsPerRenderUpdate": 4,
		"density0": 1000, 
		"simulationMethod": 4,
		"gravitation": [0,-9.81,0], 
		"cflMethod": 1, 
		"cflFactor": 1,
		"cflMaxTimeStepSize": 0.005,
		"maxIterations": 100,
		"maxError": 0.05,
		"maxIterationsV": 100,
		"maxErrorV": 0.1,		
		"stiffness": 50000,
		"exponent": 7,
		"velocityUpdateMethod": 0,
		"enableDivergenceSolver": true,
		"particleAttributes": "velocity",
		"boundaryHandlingMethod": 2
	},
	"Materials": [
		{
			"id": "Fluid",
			"colorMapType": 1,
			"surfaceTension": 0.2,
			"surfaceTensionMethod": 0,
			"viscosity": 0.01,
			"viscosityMethod": 1
		}
	],
	"RigidBodies": [
		{
			"id": 0,
			"geometryFile": "../models/UnitBox.obj",
			"translation": [0,1,0],
			"rotationAxis": [1, 0, 0],
			"rotationAngle": 0,
			"scale": [2, 2, 2],
			"color": [0.1, 0.4, 0.6, 1.0], 
			"isDynamic": false,
			"isWall": true,
			"mapInvert": true, 
			"mapThickness": 0.0,
			"mapResolution": [25,25,25]
		},
		{
			"id": 1,
			"geometryFile": "../models/UnitBox.obj",
			"translation": [0,0.1,0],
			"rotationAxis": [1, 0, 0],
			"rotationAngle": 0,
			"scale": [1,0.1,0.2],
			"color": [0.1, 0.4, 0.6, 1.0], 
			"density": 10000,
			"isDynamic": true,
			"isWall": false,
			"mapInvert": false, 
			"mapThickness": 0.0,
			"mapResolution": [20,20,20]
		}
	],
	"TargetVelocityMotorHingeJoints": [
		{
			"bodyID1": 1,
			"bodyID2": 0,
			"position": [0,0,0],
            "axis": [0,1,0],
            "target": -6
		}
	],
	"FluidBlocks": [
		{
			"denseMode": 0,
			"start": [-0.5, -0.5, -0.5],
			"end": [0.5, 0.5, 0.5],
			"translation": [0.0, 0.6, 0.0],
			"scale": [1,0.75,1]
		}
	],
	"Emitters": [
		{
			"width": 7, 
			"translation": [0.9,0.3,0.0],
			"rotationAxis": [0, 1, 0],
			"rotationAngle": 3.1415926535897932384626433832795,
			"velocity": 0.2,
			"type": 1,
			"emitStartTime": 0,
			"emitEndTime": 5
		}
	]
}
```

**Comment by janbender** [comment]
I just tested your model and for me everything works fine:

![grafik](https://user-images.githubusercontent.com/12254098/79320441-21b2fc00-7f0a-11ea-985f-cc6d6eab5954.png)

Can you give me some more information about your configuration (cmake, system)?

**Comment by harveybia** [comment]
**CMake version**
`cmake version 3.10.2`

**CMake output**
```
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- If your CPU does not support AVX, turn off the USE_AVX flag.
-- Found OpenMP_C: -fopenmp (found version "4.5") 
-- Found OpenMP_CXX: -fopenmp (found version "4.5") 
-- Found OpenMP: TRUE (found version "4.5")  
-- Build type: Release
-- Found Eigen3: /usr/include/eigen3 (Required is at least version "2.91.0") 
-- Found GLUT: /usr/lib/x86_64-linux-gnu/libglut.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Configuring done
-- Generating done
-- Build files have been written to: /home/haowensh/Projects/blaser/fluid/SPlisHSPlasH/build-test
```

**System information**
`Linux [redacted] 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Package version:**
commit 20bef647c69b28d0c7a35e57296c34e4c9c59a09 (HEAD -> master, origin/master, origin/HEAD)



I am running the Python binding splash though, could that be a problem?

**Comment by digitalillusions** [comment]
I don't know if you found the problem/ solution already but for me this works with the current version of pysplishsplash on windows. I'll try the scene on linux as soon as I get the chance.

**Comment by harveybia** [comment]
> I don't know if you found the problem/ solution already but for me this works with the current version of pysplishsplash on windows. I'll try the scene on linux as soon as I get the chance.

Thanks, I will test it on Windows too and try to figure out why this happens in the mean time

**Comment by digitalillusions** [comment]
Interesting... On linux I get the same issue that you described. I guess we'll have to look into this.

**Comment by Theodotus1243** [comment]
@janbender I'he got the same issue as described by @harveybia

I have compiled Package: commit https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/commit/f46998f11c36e3735ac44560b49e2c85dcf3e9b4 (HEAD -> master, origin/master, origin/HEAD)
Runned `./SPHSimulator ../data/Scenes/Honey.json`

This is my config [Honey.json](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/9896267/Honey.json.txt)


Without `Emitters`, `TargetVelocityMotorHingeJoints` rotates fine 
But with `Emitters` it's just infinitelly falls

**Comment by janbender** [comment]
Each emitter also adds a rigid body to the scene. I just wonder if this is initialized with id 0. Can you try to give your rigid bodies other IDs, e.g. 2 and 3?



Am 30. Oktober 2022 17:11:23 MEZ schrieb Bohdan Mykhailenko ***@***.***>:
***@***.*** I'he got the same issue as described by @harveybia

**Comment by Theodotus1243** [comment]
> 

It works, Set it to 1 and 2
Thanks for an instant responce with right fix
Happy that the issue has been resolved
And that the pacage is stable and it's more like missuse than a bug

**Comment by janbender** [comment]
I will add that to the documentation. Thanks for reporting it.
