### ISSUE TITLE
Some Confusion about Multiphase Flow

### ISSUE THREAD

**Issue by CGrapher** [InteractiveComputerGraphics/SPlisHSPlasH#69]
I'm sorry to trouble you.
I am a doctoral candidate. Your SPH library SPlisHSPlasH is very helpful to my research. I want to express my sincere thanks to you first.
Recently, I have some confusion in the study of multiphase flow based on SPH. May I ask you a few questions?
![letter2Dr  Bender2](https://user-images.githubusercontent.com/24447496/80117729-191d8e00-85ba-11ea-9b68-e3250ae6aa4a.png)
Looking forward to your guidance and advice! This question has troubled me for a long time. Thank you again.

**Comment by CGrapher** [comment]
This is an editable file：
[Some Confusion about Multiphase Flow.docx](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/4523564/Some.Confusion.about.Multiphase.Flow.docx)

**Comment by janbender** [comment]
We use the multiphase formulation of Solenthaler. There you define the density as follows:

rho_i = rho_i0 \sum V_j W_ij

That means that you assume that all particles in the neighborhood of i have the rest density of particle i. If you apply that idea to all formulas, then you end up with the SPlisHSPlasH equations. You can find more about that in our SPH tutorial: 

[Smoothed Particle Hydrodynamics Techniques for the Physics Based Simulation of Fluids and Solids](https://diglib.eg.org/bitstream/handle/10.2312/egt20191035/001-041.pdf)
