### ISSUE TITLE
Typo in CMake files (OPENGL_INCLUDE_DIRS, GLUT_INCLUDE_DIRS)?

### ISSUE THREAD

**Issue by codylico** [InteractiveComputerGraphics/SPlisHSPlasH#70]
For both "Simulator/CMakeLists.txt" and "Tools/PartioViewer/CMakeLists.txt", I find the following line:
```cmake
include_directories( ${OPENGL_INCLUDE_DIRS} ${GLUT_INCLUDE_DIRS})
```

However, the official documentation for both [FindOpenGL](https://cmake.org/cmake/help/latest/module/FindOpenGL.html) [(v3.0)](https://cmake.org/cmake/help/v3.0/module/FindOpenGL.html) and [FindGLUT](https://cmake.org/cmake/help/latest/module/FindGLUT.html) [(v3.0)](https://cmake.org/cmake/help/v3.0/module/FindGLUT.html) seem to differ (note, no final "s"):
```rst
#   GLUT_INCLUDE_DIR, where to find GL/glut.h, etc.
```
```rst
# ``OPENGL_INCLUDE_DIR``
#  Path to the OpenGL include directory.
```

The difference gave me trouble while trying to use a freshly downloaded `freeglut` with the library, because the cache variable provided by the find-package and shown by CMake (`GLUT_INCLUDE_DIR`) was not the variable used by the build (`GLUT_INCLUDE_DIRS`). I would expect the build to use the variable provided by the find-package (`GLUT_INCLUDE_DIR`), but maybe there is a reason for the difference.

I post this issue in case the difference was unintentional.

**Comment by janbender** [comment]
Freeglut is already included in the SPlisHSPlasH project. So you don't have to install it manually.

**Comment by codylico** [comment]
This is true. I noticed the freeglut included with the repository.

However, I still think the `include_directories(...)` commands need fixing.

The following:
```cmake
include_directories( ${OPENGL_INCLUDE_DIRS} ${GLUT_INCLUDE_DIRS})
```
should be:
```cmake
include_directories( ${OPENGL_INCLUDE_DIR} ${GLUT_INCLUDE_DIR})
```

**Comment by janbender** [comment]
I think the question is if it compiles or not. Btw. freeglut will be removed in the next version.

**Comment by codylico** [comment]
The version 2.8.0 update addresses this issue.  The variable names were either updated or replaced.

I apologize for any boundaries I have wrongfully crossed while posting in this issue.
