### ISSUE TITLE
PCISPH simulation is not working as expected

### ISSUE THREAD

**Issue by SunlayGGX** [InteractiveComputerGraphics/SPlisHSPlasH#71]
Hello,

When we simulate a fluid using PCISPH with default settings and any default scenes (i.e : DamBreakModel.json), the fluid explodes.

![image](https://user-images.githubusercontent.com/20280888/80610180-07e3df80-8a07-11ea-9b93-a8aea109fc87.png)

**Comment by janbender** [comment]
Seems to be a problem in combination with the volume maps boundary handling. Switch to:

"boundaryHandlingMethod": 0

And reduce the time step since PCISPH is typically far less stable than the other methods (and slower).

**Comment by SunlayGGX** [comment]
It works (but yes, it became really slower). Thank you.

**Comment by janbender** [comment]
PCISPH is really slow compared to DFSPH. If you are interested in speedup values, take a look in our paper. Btw. I would not recommend to use PCISPH. It is slow, not very stable and there are far better methods. If you want to know more, take a look here:

https://animation.rwth-aachen.de/media/papers/64/2019-EG-SPH_Tutorial.pdf
