### ISSUE TITLE
Requesting info on supported particle radii

### ISSUE THREAD

**Issue by mskr** [InteractiveComputerGraphics/SPlisHSPlasH#73]
The docs for the file format state that `"particleRadius": 0.025` is default. Can you also give upper and lower bounds?

I found that radius 0.001 (1 millimeter) causes particles to bounce with highspeed and behave chaotic. With 0.01 (10 millimeters) the jumping is completely gone and it behaves like liquid again.

**Comment by janbender** [comment]
There is no hard lower or upper bounds. If you use a very small radius, you should also think about smaller time steps. The CFL condition should automatically do this for you. However, the CFL condition, which is typically used, is just a heuristic. Therefore, I would recommend using a CFL factor clearly below 1 for such simulations.
