### ISSUE TITLE
Sticky surface

### ISSUE THREAD

**Issue by alt0216** [InteractiveComputerGraphics/SPlisHSPlasH#78]
Is there a way to make the surface sticky so that the particles don't roll much after they hit the surface?

**Comment by janbender** [comment]
Yes, you can increase the boundary viscosity.

**Comment by alt0216** [comment]
Thank you for replying, I changed the viscosityBoundary on the Buckling Weiler 2018 from 5000 to 5000000 but the particles are still rolling along the surface.

**Comment by janbender** [comment]
Sorry, maybe I misunderstood your first question. The boundary viscosity cannot guarantee that the particles do not move on the surface. It just reduces the tangential velocity. A perfect sticking is not possible at the moment. However, if you use smaller time steps, this is getting more in the direction you want.

**Comment by alt0216** [comment]
Got it, thanks.
