### ISSUE TITLE
Users list for doubts.

### ISSUE THREAD

**Issue by dineshadepu** [InteractiveComputerGraphics/SPlisHSPlasH#8]
Thanks for making such software open to use.

Is there users group, where we can ask questions related to code base.

Thanks.

**Comment by janbender** [comment]
There is no user group and I'm not sure if we can create one in Github.

**Comment by dineshadepu** [comment]
We can create one in google, if you are interested. I think this is one of the best software 
for incompressible pressure solvers for SPH.

**Comment by BluePrintRandom** [comment]
what about making a blender plugin?

this will add thousands of users, many whom code ?

**Comment by janbender** [comment]
That is a good idea. However, we have no time to implement this and not enough experience with Blender. I am even not sure if Blender supports particle systems.

**Comment by dineshadepu** [comment]
It has python-numpy support. If some way the particle positions are given to it, then it could render. 
But I don't know about real time simulation.
