### ISSUE TITLE
Graphical file selector still pops up even with --no-gui flag and a scene file in args

### ISSUE THREAD

**Issue by piyueh** [InteractiveComputerGraphics/SPlisHSPlasH#82]
I'm using the python version of the simulator (`splash`) through `pip` installation. When I executed `splash` with `--no-gui` and explicitly specified a scene file in the CMD arguments, a TK graphical file selector popped up. For example:
```
$ splash --no-gui --output-dir=${SCENES_PATH}/temp --no-initial-pause --stopAt=100 ${SCENES_PATH}/DamBreakModel_2D.json
```
However, the actual scene file used by the simulator was the one I specified in the CMD arguments.

The file selector also popped up with `splash --version`, while there should be no need for a scene file.

Not sure if I looked at the correct place, but in the code snippet [here](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/blob/56cfd290f4056ec4fc487f79bff54c6215b0fec7/pySPlisHSPlasH/scripts/simulator.py#L12-L16), it seems as long as there's no `--help` in the arguments, a file selector is always called:
https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/blob/56cfd290f4056ec4fc487f79bff54c6215b0fec7/pySPlisHSPlasH/scripts/simulator.py#L12-L16

The `splash` version is 2.8.4, and the python version is 3.8.5. The OS is Arch.

**Comment by janbender** [comment]
We just fixed that. Please try again with the new version.

**Comment by piyueh** [comment]
Thanks. The problem is gone in v2.8.5 .
