### ISSUE TITLE
Tips for simulating internal flow?

### ISSUE THREAD

**Issue by mskr** [InteractiveComputerGraphics/SPlisHSPlasH#83]
I tried to compare an Ansys Fluent simulation in the following model of a blood vessel with SplishSplash.

Here are streamlines of the Ansys result:

![image](https://user-images.githubusercontent.com/10597783/91656321-2db5e980-eab8-11ea-9b90-77c57f2ffd30.png)

SplishSplash result is basically just noise:

![image](https://user-images.githubusercontent.com/10597783/91656345-5dfd8800-eab8-11ea-876e-3595c0241bb0.png)

I have around 200k particles, the volume is nicely filled:

![image](https://user-images.githubusercontent.com/10597783/91656369-7d94b080-eab8-11ea-820e-966100d88883.png)

I used an emitter at the vessel start (in the front of the image) and set up a bounding box to reuse particles.

Boundary handling is volume map.

SplishSplash ran for a few hours before I took the snapshot.

Why is the result so far from correct? I had problems with other internal flows too and examples are all external flows. What prevents SplishSplash from simulating internal flows?

**Scene file:**

```
{
  "Configuration": {
    "pause": false,
    "cameraPosition": [ -10, 0, 10 ],
    "cameraLookAt": [ 10, 0, 0 ],
    "numberOfStepsPerRenderUpdate": 4,

    "gravitation": [ 0, 0, 0 ],

    "simulationMethod": 4,
    "particleRadius": 0.025,
    "density0": 1055,

    "timeStepSize": 0.005,
    "cflMethod": 2,
    "cflFactor": 1,
    "cflMaxTimeStepSize": 0.005,

    "enableDivergenceSolver": true,
    "maxIterations": 100,
    "maxError": 0.05,
    "maxIterationsV": 100,
    "maxErrorV": 0.1,

    "boundaryHandlingMethod": 2,

    "enableRigidBodyExport": true,
    "enablePartioExport": true,
    "particleAttributes": "velocity"
  },
  "Materials": [
    {
      "id": "Fluid",
      "surfaceTension": 0.2,
      "surfaceTensionMethod": 0,
      "viscosity": 0.01,
      "viscosityMethod": 7,

      "maxEmitterParticles": 10000,
      "emitterBoxMin": [ -5, -5, -5 ],
      "emitterBoxMax": [ 7, 5, 5 ],
      "emitterReuseParticles": true
    }
  ],
  "Emitters": [
    {
      "width": 24,
      "translation": [ -1.8, 0, 0 ],
      "velocity": 1,
      "type": 1
    }
  ],
  "RigidBodies": [
    {
      "geometryFile": "Vessel.obj",
      "color": [ 0.1, 0.4, 0.6, 0.5 ],
      "isDynamic": false,
      "isWall": false,
      "mapInvert": true
    }
  ],
  "AnimationFields": [
    {
      "particleField": "velocity",
      "translation": [ 0.5, 0, 0 ],
      "scale": [ 1, 3, 3 ],
      "shapeType": 0,
      "expression_x": "1",
      "expression_y": "",
      "expression_z": ""
    }
  ],
  "FluidModels": [
    {
      "id": "Fluid",
      "particleFile": "InnerFluid.obj"
    }
  ]
```

**Comment by janbender** [comment]
It is really hard to say what happens there. But maybe I can give a few hints to (hopefully) improve the results:

- You should use 
      "viscosityMethod": 1,
  for low viscous flow like in the scene file you attached. 

- For a higher accuracy you can use a lower max error:
     "maxError": 0.01,

- It could also help to lower the time step a bit and only use half the CFL time step:

   "cflFactor": 0.5,

- SPlisHSPlasH resorts the particles after a few steps to improve the cache use. This should be considered when visualizing the results. Otherwise particles seem to jump around. The simple solution to test if this is a problem is to deactivate the sorting:

   "enableZSort": false,

Hope that helps

**Comment by mskr** [comment]
Thanks for the tips. I followed them and also increased particleRadius to 0.1, to have faster simulation for testing. I turned out that it was neither viscosityMethod nor Z-sorting. Just bigger and fewer (6k) particles improved the result:

![image](https://user-images.githubusercontent.com/10597783/92254549-592e3f00-eed1-11ea-900a-8bd0bb001ed1.png)
