### ISSUE TITLE
Temperature-dependent viscosity in Weiler et al. 2018 

### ISSUE THREAD

**Issue by alt0216** [InteractiveComputerGraphics/SPlisHSPlasH#84]
The paper by Weiler et al. 2018 demonstrated the temperature-dependent viscosity capability of their method and gave an example of the melting bunny. Is this implemented in the current version of SPlisHSPlas? If so how may I use it. 
![image](https://user-images.githubusercontent.com/63251070/91670717-11cd3a80-eaee-11ea-81df-dfd899f77cd1.png)

**Comment by janbender** [comment]
Sorry, but we did not find the time yet to integrate this in SPlisHSPlasH.

**Comment by alt0216** [comment]
Got it, thanks.
