### ISSUE TITLE
How to change Viscosity value for certain locations and times to simulate liquid freezing? 

### ISSUE THREAD

**Issue by uljadberdica1000** [InteractiveComputerGraphics/SPlisHSPlasH#85]
What is the best way to change the viscosity level of the particles in time. I want to change it for the particles as a function of their time after their emission without affecting the rest of the system i.e particles. 

e.g Particles freeze after being emitted to simulate additive manufacturing. 

I canot find a functon to do that, how would I write one?

**Comment by janbender** [comment]
Currently all particles have the same viscosity value. So you would have to extend the framework and add a field which stores the viscosity coefficient per particle. This is quite simple:

- Add a vector<Real> m_viscoCoeffs in Viscosity_Weiler2018.h
- In Viscosity_Weiler2018.cpp each time m_viscosity is used, exchange this by m_viscoCoeffs[i]
- Write a function to update m_viscoCoeffs. This could even be done in Python using our Python binding.

**Comment by uljadberdica1000** [comment]
How do I populate the vector and then how do I know which index to increase the viscosity of? How do I know which index is for each particle for example? How many elements are pushed per step size?

**Comment by janbender** [comment]
You can take a look at the file SurfaceTension_He2014.h and how the field std::vector<Real> m_color; is used there. To identify the particle you can use its ID or its position.
