### ISSUE TITLE
CUDAException when running scene file

### ISSUE THREAD

**Issue by jasonfu4818** [InteractiveComputerGraphics/SPlisHSPlasH#86]
I build SPlisHSPlasH with `Use GPU neighborhood search" ON`. I tried to run an example scene file but I get an error with 'CUDAException'

> Output directory: /home/jason/splisplash/bin/output/CoilingModel_Weiler2018
Load scene file: /home/jason/splisplash/data/Scenes/CoilingModel_Weiler2018.json
Initialize static boundary simulation
Initialize fluid particles
Number of fluid particles: 956
OpenGL version 4.6
Using GLEW 1.12.0
Vendor: NVIDIA Corporation
Renderer: GeForce GTX 750 Ti/PCIe/SSE2
Version: 4.6.0 NVIDIA 455.23.05
terminate called after throwing an instance of 'CUDAException'
  what():  no kernel image is available for execution on the device
Aborted (core dumped)

When I run make I get the following warning but no error

> Cloning into 'Ext_GenericParameters'...
Cloning into 'Ext_Discregrid'...
-- cuNSearch::Real = float
-- Configuring done
CMake Warning (dev) in CMakeLists.txt:
  Policy CMP0104 is not set: CMAKE_CUDA_ARCHITECTURES now detected for NVCC,
  empty CUDA_ARCHITECTURES not allowed.  Run "cmake --help-policy CMP0104"
  for policy details.  Use the cmake_policy command to set the policy and
  suppress this warning.
  CUDA_ARCHITECTURES is empty for target "cuNSearch".
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Generating done
-- Build files have been written to: /home/jason/splisplash/extern/cuNSearch/src/Ext_NeighborhoodSearch-build

**Comment by janbender** [comment]
Hm, this is hard to tell. Which Cuda version did you install?

**Comment by jasonfu4818** [comment]
The issue is probably cause by CUDA 11.1. No issue after I switch to CUDA 9.0.
