### ISSUE TITLE
Do SPlisHSPlasH support OS X?

### ISSUE THREAD

**Issue by Xayahp** [InteractiveComputerGraphics/SPlisHSPlasH#88]
Hello~

I wanna know that --- Do SPlisHSPlasH support OS X? I tried to build the repo by clang and gcc but neither with success. So sad about it TAT.

Is there any solution to help build on OS X? I'd appreciate your response. Thank you so much.

Best regards.

---

**Environment:** OS X 10.15, clang12.0.0 gcc/g++9
**Error msg:**
```make
# gcc
SPlisHSPlasH-2.8.2/build/extern/Discregrid/src/Ext_Discregrid/discregrid/src/geometry/mesh_distance.cpp:8:10: fatal error: 
      'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
```
```make
# clang
SPlisHSPlasH-2.8.2/build/extern/install/NeighborhoodSearch/include/Config.h:18:11: fatal error: 
      'parallel/algorithm' file not found
        #include <parallel/algorithm>
                 ^~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by digitalillusions** [comment]
Hey, thanks for the issue, this is actually something we want to support in the future. iirc this could easily be fixed by installing libomp from homebrew for mac, and adjusting the cmake file to use use `-Xpreprocessor -fopenmp` or something similar. However, there was also another issue which prevented me from building on OSX. I'll update this issue once I know more.

**Comment by Xayahp** [comment]
Thank you ! Looking forward to hearing from you ^_^

**Comment by digitalillusions** [comment]
Hey, have a look at my fork https://github.com/digitalillusions/SPlisHSPlasH/tree/macos-fix. I'm not sure what apple is doing with OpenMP, with the most recent update a system level openmp version has suddenly appeared, but you might still need to install `libomp` from homebrew https://formulae.brew.sh/formula/libomp. If this is installed, then the version of splishsplash from my fork should work.

Let me know if there's any other issues.

**Comment by Xayahp** [comment]
I'm sorry but, it could not successfully make again.

I make it by clang, and there are four same errors occur, which are like this:

```make
/Users/polaris/Desktop/Graphics/ProcessIV_SPH/new/SPlisHSPlasH/extern/cxxopts/cxxopts.hpp:641:10: error: 
      call to function 'operator>>' that is neither visible in the template
      definition nor found by argument-dependent lookup
      in >> value;
```

the full make msg is attached below. 

[make_msg.pdf](https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/files/5485966/make_msg.pdf)

**Comment by digitalillusions** [comment]
Interesting, I haven't encountered that error before and I don't really know how to fix it right now. On all platforms I've never had an issue with cxxopts. The only thing that comes to mind with these kinds of errors is that a C++ standard flag might be missing, but this is set here https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/blob/afc32f4f5c7a64b59b785e5ac00df3698acd359b/CMake/Common.cmake#L97. What is your cmake version?

**Comment by Xayahp** [comment]
@digitalillusions 
A late reply in 2021... :-)

In the past half year I learned a lot about cmake and clang of macOS. I guess I finally got to know where the problem is. So I decide to write something here for people working on macOS that would see it in the future.

Let me draw the conclusion first: It's not recommended to try to build `SPlisHSPlasH 2.9.0` on MacOS now.

For one thing, clang 11 don't support C++17 library features `parallel`, it's unwise to build by clang, `SPlisHSPlasH 2.9.0` can be built without pain for Visual Studio 2019! For another, it is advisable to take advantages of the more powerful GPU and CPU under the Windows or Linux platform when working on a Fluid Projects, that is much quicker for both programming computing and the rendering process afterwards.

--- details ---
First of all,  it is concerning the OpenMP in MacOS. When compiling cmake projects, it's easily for MacOS programmers to suffer such error message like this: (April, 2021, with llvm clang 11 and MacOS Big Sur)
```
'omp.h' file not found
#include <omp.h>
```
even if you in fact have `omp.h` under the folder `/usr/local/include' by typing `brew install libomp`. It is because Apple Clang is not support OpenMP by default.
For this error, my solution is, not so elegant however, directly add these line in all the `CMakelists.txt` *which is a project root `CMakeLists.txt`*, to manually link the library `omp` globally.
```
include_directories(/usr/local/include)
link_directories(/usr/local/lib)
link_libraries(omp)
```
That means, you need add these line under the root `CMakeLists.txt`, as well as the external Projects that is under the `build` folder. In SPlisHSPlasH that is `PositionBasedDynamics`, `Discregrid`, `CompactNSearch`...

However, that not what really matters. What is fatal is the something occurring in the `CompactNSearch ` project.
When I fix the OpenMP issues and compiling `CompactNSearch`, the error message occurred like this:
```
fatal error: 'parallel/algorithm' file not found
       #include <parallel/algorithm>
```
I try a lot to find solution to fix it but eventually failed in vain. Unfortunately, the answer is, Clang(both Apple Clang and LLVM Clang) still don't support this *C++17 library features*. [C++ compiler support](https://en.cppreference.com/w/cpp/compiler_support). In other words, there is no way to build `SPlisHSPlasH 2.9.0` by clang currently.

But, if you still want to manage to run `SPlisHSPlasH 2.9.0` on mac, maybe you can try build by gcc/g++ :-)

**Comment by digitalillusions** [comment]
Hi @Xayahp, this is definitely on my to do list. Like you said, the issue lies also within the dependencies of splishsplash. I've been meaning to reset my old MacBook Air to get a clean MacOS dev environment again.

**Comment by ccworld1000** [comment]
It seems that there is still this problem. Can this part be switched and disabled?

**Comment by Xayah-Hina** [comment]
> It seems that there is still this problem. Can this part be switched and disabled?

please check this -> https://github.com/InteractiveComputerGraphics/CompactNSearch/issues/3#issuecomment-487420305
