### ISSUE TITLE
Reuse particles to reduce sim time?

### ISSUE THREAD

**Issue by alt0216** [InteractiveComputerGraphics/SPlisHSPlasH#89]
The scene I am trying to run takes a long time to run and I want to use the function reuse particles to speed up the simulation. It seems that the reuse particles function will remove all the particles outside the specified box, is there a method for the particle to not be considered in the simulation but still rendered (i.e. treating each particle as a rigid object?)  or maybe there's is a way for older particles to be ignore when solving for nonPressurefore because that seems to take the most time for a given sim step in my scene?

**Comment by janbender** [comment]
Maybe this could be achieved by using an AnimationField which sets the velocity to zero and keeps a constant position.

**Comment by alt0216** [comment]
Thanks. I am trying to simulate a cylindrical column where the particles stacks in layers on the perimeter of the column. Setting Particles state to AnimationField only seems to work if I do that for the every particles which seems to defeat the point of doing the simulation. I tried to set the state to AnimationField for certain amount of particles (i.e. bottom layer), their positions still change  when the top layers of particles interact with them and I am not able to get the column to stand for long no matter how high the viscosity I set using Weiler2018. I didn't set the surface tension because the result doesn't appear as what we needed.

**Comment by janbender** [comment]
I think if the AnimationField does not help, this can only be achieved by programming a few lines. First, to prevent the non-pressure methods from computing forces for inactive particles something like this is required in the non-pressure method:

if (fm->getParticleState(i) == ParticleState::Active)

Second, you can use a Python script to mark the inactive particles and reset them to their original position.
