### ISSUE TITLE
cannot open ParameterObject.h

### ISSUE THREAD

**Issue by liyunfei18** [InteractiveComputerGraphics/SPlisHSPlasH#90]
When I build the project, vs2019 reports an error and cannot open ParameterObject.h. I cannot find ParameterObject.h throughout the project. did I do something wrong？Looking forward to your reply，thanks.

**Comment by janbender** [comment]
ParameterObject.h is part of an external project which is automatically cloned by git during the build process. Did you install git?

**Comment by liyunfei18** [comment]
Thank you for your reply! Yes,I uesd git to download code with the 'git clone' command,but there is no GenericParameters folder in the extern folder. I remember that there is a GenericParameters folder in the extern folder of the old version of SPlisHSPlasH.

**Comment by janbender** [comment]
The folder moved. Now it is cloned to your build directory.
