### ISSUE TITLE
Julia interface/package

### ISSUE THREAD

**Issue by PharmCat** [InteractiveComputerGraphics/SPlisHSPlasH#92]
Hello! Do you have any plans to make [Julia](https://julialang.org/) interface?

**Comment by janbender** [comment]
Currently we don't have the time for implementing another interface. So the answer is no.

**Comment by PharmCat** [comment]
> 
> 
> Currently we don't have the time for implementing another interface. So the answer is no.

Thank you for reply! 

P.S. SPlisHSPlasH is the awesome project and there is no analogues in Julia environment.
