### ISSUE TITLE
.bin files in rigid_bodies directory

### ISSUE THREAD

**Issue by haipengyuan** [InteractiveComputerGraphics/SPlisHSPlasH#94]
I want to render the 'MotorScene' scene, and I can import the partio files into Houdini. But how do I handle the .bin files in rigid_bodies directory?
I am sorry for my lack of knowledge. And I found that SPlisHSPlash can also export VTK files. I only know that ParaView can preview the VTK files. Can VTK files be rendered？
Thanks.

**Comment by janbender** [comment]
The bin format is an own quite simple format to export the rigid body motion. If you want to know how to read it, here you find our script to load the files in Maya: 

https://github.com/InteractiveComputerGraphics/SPlisHSPlasH/blob/master/Scripts/Maya/SPlisHSPlasH.py#L1129

It is a binary file. The first file of a sequence contains information like file name of an OBJ file (which contains the geometry of the body), scaling, color. The other files only contain a translation vector and a rotation matrix. 

So either you write a similar script for Houdini to import the data or you find a appropriate file format for such a sequence and export the data in this format. I can also help if you have further questions.

**Comment by janbender** [comment]
Concerning the VTK files: you can import the VTK files in paraview (particles AND rigid bodies) and use the path tracer in Paraview to get nice results, see e.g. here:

https://blog.kitware.com/paraview-and-vtk-add-gpu-accelerated-ray-tracing-with-nvidia-rtx/

**Comment by janbender** [comment]
I spend some time to clean up the exporter code. Now it should be simple to write a new own exporter:

https://splishsplash.readthedocs.io/en/latest/implement_exporter.html

Moreover, I added an exporter to write OBJ files which can be imported in 3D modelling tools.

**Comment by haipengyuan** [comment]
This sounds great, thank you.
